<font color=red>**Danger zone:**</font> you'll be fine-tuning a model to generate positive, negative or even toxic reviews. We'll be doing this for fun, but this is also the technique for [review bombing](https://en.wikipedia.org/wiki/Review_bomb), bot farms on social media and other less than dignified stuff. It is ultimately your decision how you apply this knowledge, but before you choose, ask yourself: is this why you chose to learn ML?


# LLMs Alignment with Reinforcement Learning from human feedback (RLHF).

_based on the [original notebook](https://github.com/antndlcrx/oxford-llms-workshop/blob/main/materials/seminars/day_3/8_LLMs%20alignment%20with%20RLHF.ipynb) by Ilya Boytsov for the Oxford LLMs workshop_

In this session, you're gonna fine-tune a language model with reinforcement learning to make it generate good (or bad) reviews.

To perform RL-based fine-tuning, we'll use a new (in this course) library called [Transformer Reinforcement Learning (TRL)](https://huggingface.co/docs/trl). TRL implements the main reinforcement learning components of RLHF: reward modeling and fine-tuning with PPO.

![img](https://huggingface.co/datasets/trl-internal-testing/example-images/resolve/main/images/TRL-readme.png)

### Tutorial: align the model to generate positive movie reviews

To see how TRL works, we'll use it to align GPT2 on IMDB dataset to generate positive (or negative) movie reviews. In fact, __it's your choice whether you want positive or negative reviews.__

But before you choose, let's take a look at the baseline model: a GPT-2 fine-tuned on generating arbitrary movie reviews.

In [78]:
import torch
import transformers
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
main_tokenizer = transformers.AutoTokenizer.from_pretrained("lvwerra/gpt2-imdb")
main_model = transformers.AutoModelForCausalLM.from_pretrained("lvwerra/gpt2-imdb", device_map=device)

In [2]:
inputs = main_tokenizer("The movie", return_tensors='pt').to(device)
generated_ids = main_model.generate(**inputs, max_new_tokens=50, do_sample=True)
print("\nGenerated text:", main_tokenizer.decode(generated_ids.flatten().cpu().numpy().tolist()))

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\transformers\models\gpt2\modeling_gpt2.py:545: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(

Generated text: The movie was made in the early 1990s, the first years of the Americanization of film. While most of this movie is quite funny and makes you laugh, the bad guys are the main reasons why this movie is so bad. I have a confession to

If you run this cell a couple of times, you'll see that the model generates both positive, negative and neutral reviews in some proportion. What we're gonna do next is teach the model to generate more positive (or negative) reviews.

Similarly to InstructGPT, we're gonna do that in 2 stages:
- **train a reward model** to assign higher values to positive (or negative) reviews
- fine-tune the language model to **maximize that reward using [proximal policy optimization](https://openai.com/research/openai-baselines-ppo)**

## Stage 1: train a reward model

First, we'll train a BERT-like model as our reward model. We'll generate a synthetic pairwise rankings to emulate human rankings.

__Q:__ why do I need a reward model? Can I just use a pre-trained sentiment classifier? <br> __A:__ Yes, you can - but that only works for movie reviews. But this tutorial will teach you how to do RLHF for any kind objective.


__If you actually want to maximize sentiment (or other "label") instead of human preferences, train reward model as a classifier! (see week5)__

In [3]:
# We'll be fine-tuning a small BERT-like model for now. Please try other models for the main assignment.
reward_model = transformers.AutoModelForSequenceClassification.from_pretrained("distilbert-base-cased", device_map=device)
reward_tokenizer = transformers.AutoTokenizer.from_pretrained("distilbert-base-cased")

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

__Note that__ the reward model has a separate tokenizer, different from the main model. They don't need to be the same for RLHF fine-tuning.

In [75]:
# To train a reward model, you need a dataset (or generator) of positive-negative pairs.
# Each training sample should be a dict with 4 keys:
#  - input_ids_chosen, attention_mask_chosen = tokenizer("A sentence that human labeler likes more")
#  - input_ids_rejected, attention_mask_rejected = tokenizer("A sentence that human labeler likes less")

import torch
import datasets

class IMDBPairwiseDataset(torch.utils.data.Dataset):
    """ A dataset of all possible pairs of chosen and texts in TRT reward training format """
    def __init__(self, imdb, tokenizer, accepted_label: int):
        super().__init__()
        self.tokenizer = tokenizer
        self.chosen_texts = [row['text'] for row in imdb if row['label'] == accepted_label]
        self.rejected_texts = [row['text'] for row in imdb if row['label'] != accepted_label]
        self.column_names = ["input_ids_chosen", "attention_mask_chosen", "input_ids_rejected", "attention_mask_rejected"]
        assert self.chosen_texts, f"no texts with label {accepted_label}"
        print(f"Found {len(self.chosen_texts)} chosen and {len(self.rejected_texts)} rejected texts, {len(self)} pairs")

    def __len__(self):
        return len(self.chosen_texts) * len(self.rejected_texts)  # all pairs

    def __getitem__(self, index: int):
        chosen = self.tokenizer(self.chosen_texts[index // len(self.chosen_texts)], truncation=True)
        rejected = self.tokenizer(self.rejected_texts[index % len(self.chosen_texts)], truncation=True)
        return dict(input_ids_chosen=chosen['input_ids'], attention_mask_chosen=chosen['attention_mask'],
                    input_ids_rejected=rejected['input_ids'], attention_mask_rejected=rejected['attention_mask'])

In [76]:
TARGET_LABEL = 1   # and make sure it works by reviewing the sample printed below
imdb = datasets.load_dataset("imdb", split='train')
reward_data = IMDBPairwiseDataset(imdb, reward_tokenizer, accepted_label=TARGET_LABEL)

sample = reward_data[31337]
print('CHOSEN:', reward_tokenizer.decode(sample['input_ids_chosen']))
print('REJECTED:', reward_tokenizer.decode(sample['input_ids_rejected']))

Found 12500 chosen and 12500 rejected texts, 156250000 pairs
CHOSEN: [CLS] Lars Von Trier is never backward in trying out new techniques. Some of them are very original while others are best forgotten. < br / > < br / > He depicts postwar Germany as a nightmarish train journey. With so many cities lying in ruins, Leo Kessler a young American of German descent feels obliged to help in their restoration. It is not a simple task as he quickly finds out. < br / > < br / > His uncle finds him a job as a night conductor on the Zentropa Railway Line. His job is to attend to the needs of the passengers. When the shoes are polished a chalk mark is made on the soles. A terrible argument ensues when a passenger ' s shoes are not chalked despite the fact they have been polished. There are many allusions to the German fanaticism of adherence to such stupid details. < br / > < br / > The railway journey is like an allegory representing man ' s procession through life with all its trials and tribulations. In one sequence Leo dashes through the back carriages to discover them filled with half - starved bodies appearing to have just escaped from Auschwitz. These images, horrible as they are, are fleeting as in a dream, each with its own terrible impact yet unconnected. < br / > < br / > At a station called Urmitz Leo jumps from the train with a parceled bomb. In view of many by - standers he connects the bomb to the underside of a carriage. He returns to his cabin and makes a connection to a time clock. Later he jumps from the train ( at high speed ) and lies in the cool grass on a river bank. Looking at the stars above he decides that his job is to build and not destroy. Subsequently as he sees the train approaching a giant bridge he runs at breakneck speed to board the train and stop the clock. If you care to analyse the situation it is a completely impossible task. Quite ridiculous in fact. It could only happen in a dream. < br / > < br / > It ' s strange how one remembers little details such as a row of cups hanging on hooks and rattling away with the swaying of the train. < br / > < br / > Despite the fact that this film is widely acclaimed, I prefer Lars Von Trier ' s later films ( Breaking the Waves and The Idiots ). The bomb scene described above really put me off. Perhaps I ' m a [SEP]
REJECTED: [CLS] I saw this movie in 1979, I was 17 or 18, when it was released. The theater was perhaps 1 / 4 full when the movie started. Ten minutes into the movie me and the friend who went with me to see the film were the only two people in the theater. The movie was really weird and had no plot or reason to its script and people demanded their money back. We decided to stay for the ENTIRE movie.... why endure such torture??... here ' s why. We wanted to be true movie critics... to have a standard to base all other movies on it is hard to justify saying you have seen the best movie ( a 10 ) they always come up with something better. But, it is easy to be able to base all other movies off of the worst movie ever made ( and this is it... a 1 at best ). There may be other movies out there that truly qualify as a 1, but I have yet to see them. I now base all movies I see on a scale based on this worst.... I AM A TRUE MOVIE CRITIC... he he. [SEP]

We'll be using `trl.RewardTrainer` - a special case of `transformers.Trainer` that you used in the past. `RewardTrainer` accepts the same format of training arguments (e.g. batch size, gradient checkpointing) as before, except that it trains the model for the pairwise reward objective from [the InstructGPT paper](https://arxiv.org/pdf/2203.02155.pdf):

![img](https://i.imgur.com/2JzNAPs.png)

Note that the model itself does not score pairs: it processes chosen ($y_w$) and rejected ($y_l$) samples independently. To minimize this loss, the reward model needs to score chosen sample higher than the rejected one. Note that the formula also assumes some context $x$, which is useful for seq2seq tasks. In our case of movie reviews, $x$ is empty.

In [6]:
import trl

training_args = trl.RewardConfig(  # like transformers.TrainingArguments
    output_dir="reward_model",
    per_device_train_batch_size=32,
    gradient_accumulation_steps=1,
    learning_rate=1.41e-5,
    max_steps=1_000,              # note: training may need more than 1k steps
    logging_steps=50,
    gradient_checkpointing=True,  # reduce memory usage but train ~30% slower
    gradient_checkpointing_kwargs={"use_reentrant": False},
    fp16=True                     # disable this on CPU or on very old GPUs
    # you may add any other hyperparameters that you found useful in weeks 5-7
)

trainer = trl.RewardTrainer(
    model=reward_model,
    args=training_args,
    tokenizer=reward_tokenizer,
    train_dataset=reward_data,
    peft_config=None,  # optionally, you may tune with LoRA, prompt-tuning, etc
)

trainer.train()

C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\trl\trainer\reward_trainer.py:182: UserWarning: When using RewardDataCollatorWithPadding, you should set `max_length` in RewardConfig. It will be set to `512` by default, but you should do it yourself in the future.
  warnings.warn(
C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\trl\trainer\reward_trainer.py:199: UserWarning: When using RewardDataCollatorWithPadding, you should set `remove_unused_columns=False` in your RewardConfig we have set it for you, but you should do it yourself in the future.
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: aleksegorov1312 (aleksegorov1312-aimasters). Use `wandb login --relogin` to force relogin

You're using a DistilBertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\transformers\tokenization_utils_base.py:2847: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\transformers\tokenization_utils_base.py:2847: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

TrainOutput(global_step=1000, training_loss=0.10799304509162903, metrics={'train_runtime': 1339.0845, 'train_samples_per_second': 23.897, 'train_steps_per_second': 0.747, 'total_flos': 0.0, 'train_loss': 0.10799304509162903, 'epoch': 0.00020479997902848215})

In [7]:
reward_model.gradient_checkpointing_disable()
reward_model.eval()

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
with open("./reward_model_checkpoint.pth", "wb") as fp:
    torch.save(reward_model.state_dict(), fp)

### Sanity-check the reward model (1 point)

Let's check how our reward model performs.

__Your task__ is to measure how often does your reward model can rank a pair of (chosen and rejected) reviews correctly. Please measure this separately for train data (`imdb`) and a separate test set loaded below.

In [8]:

for sample_index in 45, 16000:
  print('TEXT:', imdb[sample_index]['text'])
  inputs = reward_tokenizer(
      imdb[sample_index]['text'], truncation=True, return_tensors='pt').to(device)
  with torch.no_grad():
    reward = reward_model(**inputs).logits[0, 0].item()
    print("REWARD:", reward)
  print('LABEL:', imdb[sample_index]['label'])
  print()

# note: your reward model may produce different absolute rewards.
# This is fine as long as the rewards are ordered correctly (most of the time)

TEXT: This movie sucked. It really was a waste of my life. The acting was atrocious, the plot completely implausible. Long, long story short, these people get "terrorized" by this pathetic "crazed killer", but completely fail to fight back in any manner. And this is after they take a raft on a camping trip, with no gear, and show up at a campsite that is already assembled and completely stocked with food and clothes and the daughters headphones. Additionally, after their boat goes missing, they panic that they're stuck in the woods, but then the daughters boyfriend just shows up and they apparently never consider that they could just hike out of the woods like he did to get to them. Like I said, this movie sucks. A complete joke. Don't let your girlfriend talk you into watching it.
REWARD: -5.28125
LABEL: 0

TEXT: Good: Engaging cinematic firefights, great presentation, vehicles are actually fun to drive, fairly appealing multiplayer, faithful to the movie, and the list goes on.<br /><br />Bad: Main missions are a bit short.<br /><br />This game defines what a "good" third person shooter(not necessarily a spy-game) is. Great firefights carry on the story and make you want to complete EVERY single mission through, and unlock all the genuine bonuses the game has to offer. The hype this game had, was lived up to, and I personally think you should buy it, and hook up with a couple of friends and play this one. Loads of fun. <br /><br />The sound in this game, is a rip-roaring achievement from a few previous bond games, and firing a weapon, really feels like you're firing a weapon. It ties in with the aspect that you are a deadly and ruthless spy.<br /><br />All in all, this game makes you excited and satisfied after you make it through, and some multiplayer that can compete with the standards of the crafty James Bond "Nightfire" game for gamecube.
REWARD: 4.73828125
LABEL: 1

In [17]:
import pandas as pd
def reward_sanity_check(imdb, labels=None):
    if labels is None:
        labels = []
        rewards = []
    for i in imdb:
        labels.append(i["label"])
        inputs = reward_tokenizer(
          i['text'], truncation=True, return_tensors='pt').to(device)
        with torch.no_grad():
            reward = reward_model(**inputs).logits[0, 0].item()
            rewards.append(reward)
    return labels, rewards 
    
labels, rewards = reward_sanity_check(imdb)

In [29]:
stat = pd.DataFrame([labels, rewards]).T.rename(columns={0:"label", 1:"reward"})
stat

       label    reward
0        0.0 -1.159180
1        0.0 -5.218750
2        0.0 -5.058594
3        0.0 -2.062500
4        0.0 -5.039062
...      ...       ...
24995    1.0 -1.995117
24996    1.0  2.736328
24997    1.0  4.871094
24998    1.0  1.620117
24999    1.0  4.273438

[25000 rows x 2 columns]

### Train Так как целевая метка 1, то 0 в основном должна иметь отрицательный reward:

In [37]:
stat[(stat["label"] == 0) & (stat["reward"]<=0)].shape[0]/stat[(stat["label"] == 0)].shape[0]

0.95072

### Train Так как целевая метка 1, то 1 в основном должна иметь положительный reward:

In [39]:
stat[(stat["label"] == 1) & (stat["reward"]>0)].shape[0]/stat[(stat["label"] == 1)].shape[0]

0.91904

In [42]:
imdb_test = datasets.load_dataset("imdb", split='test')
labels, rewards = reward_sanity_check(imdb_test)
# <a whole lot of your code here, feel free to spit it as you see fit>

### Test Так как целевая метка 1, то 0 в основном должна иметь отрицательный reward:

In [43]:
stat = pd.DataFrame([labels, rewards]).T.rename(columns={0:"label", 1:"reward"})
stat[(stat["label"] == 0) & (stat["reward"]<=0)].shape[0]/stat[(stat["label"] == 0)].shape[0]

0.92616

### Test Так как целевая метка 1, то 1 в основном должна иметь положительный reward:

In [45]:
stat[(stat["label"] == 1) & (stat["reward"]>0)].shape[0]/stat[(stat["label"] == 1)].shape[0]

0.89648

### Высокая доля правильных ответов

### Reward-guided generation (1 point)

If you did everything right, by now you should have a decent reward model. Before we use it for reinforcement learning, let's see if we can align model samples without any training.

To do so, you can use reward-guided inference: __generate N=16 samples, then select the one with the highest reward__ (according to your reward model).

For this problem, it's on you to demonstrate whether or not your code works. Find at least 5 neutral prompts such as "This movie is" (...), generate samples, rank them based on reward and show which samples get the highest reward.

Note: it is faster to generate samples in parallel, rather than sequentially, as follows:

In [57]:
inputs = main_tokenizer(["It was"] * 5, return_tensors='pt').to(device)
for candidate in main_model.generate(**inputs, max_new_tokens=50, do_sample=True):
  print("Sample:", main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()))

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Sample: It was like this movie is trying to show you something about the Vietnam war. You see what it was like, and you know it was a terrible one-sided movie. This movie is about an American who went into war with no real plan and he didn
Sample: It was such a shock to me, when I heard all the other people talk about it.<br /><br />However, this was one of my first movies to use a real-time projection system because I felt they'd use this technology much better in
Sample: It was an amazing experience. I highly recommend this movie for all the viewers that want some laughs, with it's realistic and interesting characters. Also, this movie is worth catching on cable TV/demand TV. It definitely has some real laughs. However, in
Sample: It was a fun film, if hardly the most original of the "R-rated series," "Hollywood Movie" with many of the early-twenties teen-comic-fan boys and, to an extent, kids with more mature sensibilities
Sample: It was wonderful film. I don't really pay attention to things like plot and story line and characters until I find them. This isn't supposed to happen, it's about time in the movie.<|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|><|endoftext|>

In [15]:
def generate_examples(prompt:str, N:int):
    examples = []
    inputs = main_tokenizer([prompt] * N, return_tensors='pt').to(device)

    return [main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.generate(**inputs, max_new_tokens=50, do_sample=True)]

def get_max_reward(examples):
    rewards = {}
    for i in examples:
        inputs = reward_tokenizer(
              i, truncation=True, return_tensors='pt').to(device)
        with torch.no_grad():
            reward = reward_model(**inputs).logits[0, 0].item()
            rewards[i] = reward
    max_reward_text = max(rewards, key=rewards.get)
    return {max_reward_text: rewards[max_reward_text]}


main_model.generation_config = GenerationConfig()
examples = generate_examples("It was", 16)

In [87]:
examples = generate_examples("It was", 16)
max_reward = get_max_reward(examples)
max_reward

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

{"It was very easy to catch up with the other episodes. They were all very good, both with the original show and now with Season 9. I loved the show, which was such a different show and the story was great. I've seen that episode twice": 4.625}

In [89]:
examples = generate_examples("The movie", 16)
max_reward = get_max_reward(examples)
max_reward

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

{"The movie is so well-made it's easy to understand why so many critics have picked it up instead of reworking it for TV. It's a wonderfully constructed, well paced action drama with very good dialogue, action, suspense, and an open ending that": 4.80078125}

In [90]:
examples = generate_examples("The beginning of the film", 16)
max_reward = get_max_reward(examples)
max_reward

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

{'The beginning of the film is very touching and touching. The story line in the film, which involves that of the three young parents (from various other backgrounds), is pretty easy to relate to and, as you move to the next part and the finale, it gets even better': 4.61328125}

In [93]:
examples = generate_examples("By the end of the movie", 16)
max_reward = get_max_reward(examples)
max_reward

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

{'By the end of the movie, we get to see how the kids got to be such good and so powerful. This movie is a testament to the power of movies. This could have been a good movie, if the story had been like this. The acting was perfect and the': 4.6953125}

In [95]:
examples = generate_examples("I want to tell you", 16)
max_reward = get_max_reward(examples)
max_reward

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

{'I want to tell you that I loved this film. The scene with the girls (who were very talented in front of a camera and made perfect faces) making their voices are amazing. The script is well written with lots of action and comedy moments along with some beautiful images of': 4.78125}

### Отзывы положительные - как и выбрано в начале.

# Stage 2: fine-tune the main model with RL


For this tutorial, we will optimize GPT2 to produce positive IMDB movie reviews using the reward model you trained above.

Unlike supervised fine-tuning, RL allows model to generate it's own sentences on each training step. Then, it calculates the reward of those specific sentences, and finally, updates the model to increase the probability of sentences with high reward.

Thus, each RLHF consists of three stages: __Rollout__, __Evaluation__ and __Update__

<div style="text-align: center">
<img src='https://huggingface.co/datasets/trl-internal-testing/example-images/resolve/main/images/gpt2_bert_training.png' width='600'>

The update stage depends on the specific RL algorithm. We'll be using Proximal Policy Optimization, or [PPO](https://arxiv.org/abs/1707.06347), similarly to what was used for InstructGPT.

Before we run those 3 stages, however, we need to create a dataset of "queries" - partial reviews in our case.

In [79]:
# Note: this code is specific to IMDB; you will need to re-write it for other tasks
import trl
imdb_for_rlhf = imdb.filter(lambda row: len(row['text']) > 200, batched=False)
imdb_for_rlhf = imdb_for_rlhf.remove_columns(['label'])
sample_length = trl.core.LengthSampler(2, 8)  # use the first 2-8 tokens as query

def select_query_and_tokenize(sample):
    query_ids = main_tokenizer.encode(sample["text"])[: sample_length()]
    sample["query"] = main_tokenizer.decode(query_ids)  # query is the only required column
    sample["input_ids"] = query_ids  # to avoid re-tokenizing later
    return sample  # we do not need the rest - it will be generated by the model

imdb_for_rlhf = imdb_for_rlhf.map(select_query_and_tokenize, batched=False)
imdb_for_rlhf.set_format(type="torch")

Map:   0%|          | 0/24895 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (1168 > 1024). Running this sequence through the model will result in indexing errors

Next, let's prepare your reward model to predict rewards on whatever reviews were generated. Note that we use plaintext reviews because main model uses a different tokenizer from the reward model.

In [7]:
with open("./reward_model_checkpoint.pth", "rb") as fp:
    state_dict = torch.load(fp, map_location="cpu")
    reward_model.load_state_dict(state_dict)
    reward_model = reward_model.to(device)

In [22]:
from typing import List
def compute_reward(texts: List[str]) -> torch.Tensor:
  inputs = reward_tokenizer(texts, truncation=True, padding=True, return_tensors='pt').to(device)
  with torch.no_grad():
    return reward_model(**inputs).logits[:, 0]

In [9]:
compute_reward([imdb[45]['text'], imdb[16000]['text']])  # test on human-written reviews

tensor([-5.3548,  4.3998], device='cuda:0')

Finally, we move to RL training. In this tutorial, we'll train LoRA adapters and not the full model.

In [10]:
import peft
peft_config = peft.LoraConfig(
    task_type=peft.TaskType.CAUSAL_LM, r=32, lora_alpha=32, lora_dropout=0.0, inference_mode=False
)

# reload main model as AutoModelForCausalLMWithValueHead - with an extra head needed for PPO
main_tokenizer = transformers.AutoTokenizer.from_pretrained("lvwerra/gpt2-imdb")
main_tokenizer.pad_token = main_tokenizer.eos_token

main_model = trl.AutoModelForCausalLMWithValueHead.from_pretrained("lvwerra/gpt2-imdb", device_map=device)
main_model = peft.get_peft_model(main_model, peft_config, adapter_name='default')
main_model.print_trainable_parameters()

C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\peft\tuners\lora.py:475: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

trainable params: 1,179,648 || all params: 125,620,225 || trainable%: 0.9390589771670923

Same as before, trl has a special type of trainer that minimize PPO-specific pseudo-loss. You can read more on this trainer [here](https://huggingface.co/docs/trl/main/en/ppo_trainer).

In [11]:
training_args = trl.PPOConfig(
    model_name=main_model.config._name_or_path,
    gradient_accumulation_steps=1,
    learning_rate=1.41e-5,
    ppo_epochs=4,
    mini_batch_size=64,
    batch_size=64,# PPO performs this many updates per training batch
)

ppo_trainer = trl.PPOTrainer(
    training_args, model=main_model.model, tokenizer=main_tokenizer, ref_model=None,
    dataset=imdb_for_rlhf, data_collator=lambda data: dict((key, [d[key] for d in data]) for key in data[0])
)  # note: we pass main_model.model because PPOTrainer checks for one of several supported model types ...
# ... main_model.model is a model with adapters, which is supported. main_model itself is a wrapper that is not supported

In [12]:
from tqdm.auto import tqdm
max_steps = 50   # can be insufficient for some tasks - watch your learning curves
generation_kwargs = dict(
    min_length=-1, max_new_tokens=120, do_sample=True, top_k=0, top_p=1.0, pad_token_id=main_tokenizer.eos_token_id,
eos_token_id=main_tokenizer.eos_token_id,)
#                                  ^-- task-specific parameter!
with tqdm(enumerate(ppo_trainer.dataloader), total=max_steps) as progressbar:
  # note: ppo_trainer.dataloader is just a regular dataloader of queries, no RL-specific magic :)
  for epoch, batch in progressbar:
    if epoch >= max_steps:
        break

    # Rollout stage: generate continuations from batch queries using main_model
    response_tensors = ppo_trainer.generate(batch['input_ids'], **generation_kwargs)
    # ^-- list of tensors of token ids from main model tokenizer

    # de-tokenize responses to strings (since reward model uses a different tokenizer)
    batch["response"] = [main_tokenizer.decode(response.squeeze()) for response in response_tensors]
    # note: response_tensors already contain query tokens, so we don't need to add queries manually.
    # This may not be true for other tasks: check this manually by viewing batch["response"] and batch["query"]
    # Evaluation stage
    rewards = compute_reward(batch['response'])
    # Update stage
    stats = ppo_trainer.step(batch['input_ids'], response_tensors, list(rewards.split(1)))
    stats['rewards/mean'] = rewards.mean().item()

    print("-" * 30, 'STEP', epoch, '-' * 30)
    print(f'rewards/mean:\t{stats["rewards/mean"]:.9f}\t<---- average reward over this batch (higher=better, noisy)')
    print(f'ppo/returns/mean:\t{stats["ppo/returns/mean"]:.9f}\t<---- model-estimated average discounted reward')
    print(f'objective/kl:\t{stats["objective/kl"]:.9f}\t<---- how far we are from the original model (regularizer)')
    print()

    ppo_trainer.log_stats(stats, batch, list(rewards.split(1)))

  0%|          | 0/50 [00:00<?, ?it/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

------------------------------ STEP 0 ------------------------------
rewards/mean:	-0.762633264	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.856959820	<---- model-estimated average discounted reward
objective/kl:	0.000000000	<---- how far we are from the original model (regularizer)

------------------------------ STEP 1 ------------------------------
rewards/mean:	-0.194964558	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.109931469	<---- model-estimated average discounted reward
objective/kl:	0.004979739	<---- how far we are from the original model (regularizer)

------------------------------ STEP 2 ------------------------------
rewards/mean:	-0.071071565	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.122048020	<---- model-estimated average discounted reward
objective/kl:	0.009733500	<---- how far we are from the original model (regularizer)

------------------------------ STEP 3 ------------------------------
rewards/mean:	0.084777914	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.141216516	<---- model-estimated average discounted reward
objective/kl:	0.014173454	<---- how far we are from the original model (regularizer)

------------------------------ STEP 4 ------------------------------
rewards/mean:	-0.258754969	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.060284615	<---- model-estimated average discounted reward
objective/kl:	0.004552503	<---- how far we are from the original model (regularizer)

------------------------------ STEP 5 ------------------------------
rewards/mean:	0.048148740	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.152898908	<---- model-estimated average discounted reward
objective/kl:	0.019301793	<---- how far we are from the original model (regularizer)

------------------------------ STEP 6 ------------------------------
rewards/mean:	-0.546594381	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.925229311	<---- model-estimated average discounted reward
objective/kl:	0.014046279	<---- how far we are from the original model (regularizer)

------------------------------ STEP 7 ------------------------------
rewards/mean:	0.068728782	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.131411195	<---- model-estimated average discounted reward
objective/kl:	0.014901661	<---- how far we are from the original model (regularizer)

------------------------------ STEP 8 ------------------------------
rewards/mean:	0.095350444	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.099345922	<---- model-estimated average discounted reward
objective/kl:	0.024285985	<---- how far we are from the original model (regularizer)

------------------------------ STEP 9 ------------------------------
rewards/mean:	-0.958461523	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.786146164	<---- model-estimated average discounted reward
objective/kl:	0.038570702	<---- how far we are from the original model (regularizer)

------------------------------ STEP 10 ------------------------------
rewards/mean:	-0.624027133	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.930987477	<---- model-estimated average discounted reward
objective/kl:	0.066616826	<---- how far we are from the original model (regularizer)

------------------------------ STEP 11 ------------------------------
rewards/mean:	0.161645278	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.138325453	<---- model-estimated average discounted reward
objective/kl:	0.021615917	<---- how far we are from the original model (regularizer)

------------------------------ STEP 12 ------------------------------
rewards/mean:	-0.239018708	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.967991471	<---- model-estimated average discounted reward
objective/kl:	0.066700377	<---- how far we are from the original model (regularizer)

------------------------------ STEP 13 ------------------------------
rewards/mean:	-0.258012235	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.970662713	<---- model-estimated average discounted reward
objective/kl:	0.060897842	<---- how far we are from the original model (regularizer)

------------------------------ STEP 14 ------------------------------
rewards/mean:	0.295400470	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.218391657	<---- model-estimated average discounted reward
objective/kl:	0.062599540	<---- how far we are from the original model (regularizer)

------------------------------ STEP 15 ------------------------------
rewards/mean:	0.332928538	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.180212259	<---- model-estimated average discounted reward
objective/kl:	0.099080563	<---- how far we are from the original model (regularizer)

------------------------------ STEP 16 ------------------------------
rewards/mean:	-0.282136798	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.049863100	<---- model-estimated average discounted reward
objective/kl:	0.031337976	<---- how far we are from the original model (regularizer)

------------------------------ STEP 17 ------------------------------
rewards/mean:	0.157087177	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.182596922	<---- model-estimated average discounted reward
objective/kl:	0.045969337	<---- how far we are from the original model (regularizer)

------------------------------ STEP 18 ------------------------------
rewards/mean:	-0.442246020	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.890277743	<---- model-estimated average discounted reward
objective/kl:	0.164548591	<---- how far we are from the original model (regularizer)

------------------------------ STEP 19 ------------------------------
rewards/mean:	-0.157438725	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.986960530	<---- model-estimated average discounted reward
objective/kl:	0.161448434	<---- how far we are from the original model (regularizer)

------------------------------ STEP 20 ------------------------------
rewards/mean:	-0.222009301	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.955295086	<---- model-estimated average discounted reward
objective/kl:	0.109372675	<---- how far we are from the original model (regularizer)

------------------------------ STEP 21 ------------------------------
rewards/mean:	0.608048379	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.301198959	<---- model-estimated average discounted reward
objective/kl:	0.089340828	<---- how far we are from the original model (regularizer)

------------------------------ STEP 22 ------------------------------
rewards/mean:	-0.163829327	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.945507526	<---- model-estimated average discounted reward
objective/kl:	0.175406754	<---- how far we are from the original model (regularizer)

------------------------------ STEP 23 ------------------------------
rewards/mean:	0.444212615	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.189517260	<---- model-estimated average discounted reward
objective/kl:	0.165319353	<---- how far we are from the original model (regularizer)

------------------------------ STEP 24 ------------------------------
rewards/mean:	-0.253088385	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.967997432	<---- model-estimated average discounted reward
objective/kl:	0.247249991	<---- how far we are from the original model (regularizer)

------------------------------ STEP 25 ------------------------------
rewards/mean:	0.375837386	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.093868971	<---- model-estimated average discounted reward
objective/kl:	0.095018707	<---- how far we are from the original model (regularizer)

------------------------------ STEP 26 ------------------------------
rewards/mean:	1.214398026	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.391788006	<---- model-estimated average discounted reward
objective/kl:	0.190082297	<---- how far we are from the original model (regularizer)

------------------------------ STEP 27 ------------------------------
rewards/mean:	-0.091476470	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.995069861	<---- model-estimated average discounted reward
objective/kl:	0.138642609	<---- how far we are from the original model (regularizer)

------------------------------ STEP 28 ------------------------------
rewards/mean:	0.092770398	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.043398499	<---- model-estimated average discounted reward
objective/kl:	0.187218457	<---- how far we are from the original model (regularizer)

------------------------------ STEP 29 ------------------------------
rewards/mean:	-0.389083207	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.851521194	<---- model-estimated average discounted reward
objective/kl:	0.125871480	<---- how far we are from the original model (regularizer)

------------------------------ STEP 30 ------------------------------
rewards/mean:	-0.123230964	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.930103362	<---- model-estimated average discounted reward
objective/kl:	0.207160667	<---- how far we are from the original model (regularizer)

------------------------------ STEP 31 ------------------------------
rewards/mean:	-0.270758569	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.921664596	<---- model-estimated average discounted reward
objective/kl:	0.185770154	<---- how far we are from the original model (regularizer)

------------------------------ STEP 32 ------------------------------
rewards/mean:	-0.179991856	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.913671017	<---- model-estimated average discounted reward
objective/kl:	0.301204741	<---- how far we are from the original model (regularizer)

------------------------------ STEP 33 ------------------------------
rewards/mean:	-0.274591148	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.837457657	<---- model-estimated average discounted reward
objective/kl:	0.226117894	<---- how far we are from the original model (regularizer)

------------------------------ STEP 34 ------------------------------
rewards/mean:	0.009555772	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.885761857	<---- model-estimated average discounted reward
objective/kl:	0.384036362	<---- how far we are from the original model (regularizer)

------------------------------ STEP 35 ------------------------------
rewards/mean:	0.048869222	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.980609775	<---- model-estimated average discounted reward
objective/kl:	0.295346797	<---- how far we are from the original model (regularizer)

------------------------------ STEP 36 ------------------------------
rewards/mean:	-0.128265053	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.944986820	<---- model-estimated average discounted reward
objective/kl:	0.466023743	<---- how far we are from the original model (regularizer)

------------------------------ STEP 37 ------------------------------
rewards/mean:	0.399783462	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.036585093	<---- model-estimated average discounted reward
objective/kl:	0.044758175	<---- how far we are from the original model (regularizer)

------------------------------ STEP 38 ------------------------------
rewards/mean:	0.176871300	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.948539376	<---- model-estimated average discounted reward
objective/kl:	-0.021127218	<---- how far we are from the original model (regularizer)

------------------------------ STEP 39 ------------------------------
rewards/mean:	0.040899664	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.881784379	<---- model-estimated average discounted reward
objective/kl:	0.403914481	<---- how far we are from the original model (regularizer)

------------------------------ STEP 40 ------------------------------
rewards/mean:	0.656061292	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.059112072	<---- model-estimated average discounted reward
objective/kl:	0.283879936	<---- how far we are from the original model (regularizer)

------------------------------ STEP 41 ------------------------------
rewards/mean:	0.853646934	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.153079033	<---- model-estimated average discounted reward
objective/kl:	0.309509099	<---- how far we are from the original model (regularizer)

------------------------------ STEP 42 ------------------------------
rewards/mean:	-0.374724865	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.688442230	<---- model-estimated average discounted reward
objective/kl:	0.187178165	<---- how far we are from the original model (regularizer)

------------------------------ STEP 43 ------------------------------
rewards/mean:	0.464977682	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.994076967	<---- model-estimated average discounted reward
objective/kl:	0.261423320	<---- how far we are from the original model (regularizer)

------------------------------ STEP 44 ------------------------------
rewards/mean:	0.379598558	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.954735518	<---- model-estimated average discounted reward
objective/kl:	0.506281495	<---- how far we are from the original model (regularizer)

------------------------------ STEP 45 ------------------------------
rewards/mean:	0.308753848	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.895423770	<---- model-estimated average discounted reward
objective/kl:	0.125291556	<---- how far we are from the original model (regularizer)

------------------------------ STEP 46 ------------------------------
rewards/mean:	0.197906002	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.852919221	<---- model-estimated average discounted reward
objective/kl:	0.224441260	<---- how far we are from the original model (regularizer)

------------------------------ STEP 47 ------------------------------
rewards/mean:	0.052998751	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.784778953	<---- model-estimated average discounted reward
objective/kl:	0.389640927	<---- how far we are from the original model (regularizer)

------------------------------ STEP 48 ------------------------------
rewards/mean:	0.238837570	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.873738527	<---- model-estimated average discounted reward
objective/kl:	0.286825508	<---- how far we are from the original model (regularizer)

------------------------------ STEP 49 ------------------------------
rewards/mean:	0.458933294	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.920288980	<---- model-estimated average discounted reward
objective/kl:	-0.233830631	<---- how far we are from the original model (regularizer)

In [43]:
ref_model = trl.AutoModelForCausalLMWithValueHead.from_pretrained("lvwerra/gpt2-imdb", device_map=device)
new = 0
old = 0
for i in range(10):

    inputs = main_tokenizer(["This film"] * 16, return_tensors='pt').to(device)

    new += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()
    old += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [46]:
print("mean reward before:", old/10)
print("mean reward after:", new/10)

mean reward before: tensor(0.6024, device='cuda:0')
mean reward after: tensor(1.4407, device='cuda:0')

## Main assignment - <u>actually</u> train the model (8 points)


Your main task for this week is to use the RLHF pipeline to train a model for a reward of your choice. Here's what you can choose from:

__A. Toxicity fine-tuning:__ train the model to be less (or more!) toxic. For this task, you may use the data from [jigsaw toxic comments](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge) and [lmsys/toxic-chat](https://huggingface.co/datasets/lmsys/toxic-chat),  or any other source. Alternatively, you may use toxicity scores from [oasst1](https://huggingface.co/datasets/OpenAssistant/oasst1).


__B. Actual human feedback:__ use one of the existing datasets with pairwise human feedback to align your langauge model. You may use [anthropic's hh-rlhf](https://huggingface.co/datasets/Anthropic/hh-rlhf), [OpenAssistant dataset](https://huggingface.co/datasets/OpenAssistant/oasst1) or any other data you see fit. You may also turn the tables and train the model to [minimize](https://habrastorage.org/getpro/geektimes/post_images/ac7/2ad/827/ac72ad82767d4132164a4b6b76196c42.jpg) human preferences, as long as your model does not degrade to gibberish.

__C. Controlled generation:__ Instead of training a reward model from human feedback, you may define the reward function as the text length (longer or shorter) or number of times the model uses specific words (e.g. "sorry", "apologize"). If you choose specific words, make sure the model generates them at least sometimes.

__Alternatively,__ you may choose a different task. However, unless your task is very similar to one of the above, there is a chance that it will be **significantly** harder to solve, requiring orders of magnitude more compute and tuning. If you are in doubt, please ask the course staff. If they are AFK (again >.<), please prefer one of the recommended tasks.


#### General tips & tricks


Things to look out for:
- during PPO stage, the reward model should be in eval mode (dropout disabled)
- make sure max_length and max_new_tokens are enough for your chosen dataset - at least most of the time
- when in doubt, view the data manually or inspect how the model performs on a few samples


We highly recommend that you manually check the performance after each sub-stage:
1. when you assembled the pairwise dataset, inspect a couple of from of *your* dataset class and detokenize them. Make sure that you-the-human understand why one sample was accepted and the other - rejected. At least most of the time. This also lets you spot tokenization/truncation errors.
2. after you trained a reward model, measure how accurate this model is in isolation. If your reward model is poor, any subsequent RLHF will also fail.
3. once you've trained the main model with RL, ask it to generate examples and explore how well it does. If it produces an obviously bad output, check if the reward model assigns high reward to that output. If yes, reward model is the culprit; if no, it's a question of better/longer PPO training.

__It is also a good idea to periodically print samples during training.__

__When stuck, simplify the problem.__ If you've spent a several hours enchanting the reward model but it still won't budge, try switching to a simple subtask. For instance, if you're training on hh-rlhf, try limiting it the dataset to 10% of the shortest sequences - they are typically easier to learn.


## Assignment stages (and grading)

Regardless of the specific task you chose, your solution needs to contain several parts that will be graded separately.


#### Stage 1: reward model (4 points)

Construct a dataset for training the reward model on your problem. Then, train a reward model on that dataset and evaluate how well can your model predict preferences on a hold-out (test) subset of your data.

Please make sure that the part of your notebook where you evaluate reward model is clearly visible and reasonably easy to read. And for all that is holy, do not call it IMDB unless it actually **is** data of imdb movie reviews :)

__Not all tasks require a reward model for later PPO fine-tuning.__ For instance, there's no reason to train a reward model if your reward equals sentence length. Likewise, toxicity reward can be estimated with a pre-trained toxicity classifier. __If your task does not require training a reward model, please train an unrelated model on [hh-rlhf](https://huggingface.co/datasets/Anthropic/hh-rlhf) as though you were solving assignment version B.__ This is for grading purposes only, you won't use this model for stage 2.


#### Stage 2: RL fine-tuning (4 points)

Once the reward model is ready - or you can compute rewards without a model - it is time to maximize that reward with PPO. Optionally, you may replace PPO with another RL algorithm (or unlikelihood learning scheme), but only if you're feeling adventurous.


First, you need to choose a language model to be fine-tuned. You may choose any model, but make sure that your model **can** generate the data in your format. For instance, [Mistral-7B](https://huggingface.co/mistralai/Mistral-7B-v0.1) is a general purpose LM and may (or may not) need prompt engineering to generate chat assistant responses. For that reason, it is best if you **do not use `"lvwerra/gpt2-imdb"` unless you're generating only movie reviews**.



There are two "difficulty modes" for this task:
For the **easy mode**, use [gpt2-large](https://huggingface.co/gpt2-large) or [opt-1.3b](https://huggingface.co/facebook/opt-1.3b) with minimal code changes.
If you want the **Hard mode:** use a larger (e.g. 7B) model in combination with `load_in_4bit` and LoRA, the same way we did last week.
Some reasonable model choices are [LLaMA-7B](https://huggingface.co/Enoch/llama-7b-hf), [Falcon-7b](https://huggingface.co/tiiuae/falcon-7b), [Mistral-7B](https://huggingface.co/mistralai/Mistral-7B-v0.1) for general-purpose LM or [guanaco-7b](https://huggingface.co/timdettmers/guanaco-7b), [vicuna-7b](https://huggingface.co/lmsys/vicuna-7b-v1.5) for chat-based tasks, though there are many more (see [leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard)). In the hard mode, you will need to modify the training arguments to enable 4-bit fine-tuning. Furthermore, your experiments will take somewhat longer to complete. On the plus side, your model will produce significantly better results.

__High reward is not enough!__ RL algorithms are famous for [cheating their reward functions](https://openai.com/research/faulty-reward-functions). To ensure that your model is actually doing what you want it to do, you will need some additional evaluation. To get the full grade, provide at least 20 side-by-side examples of your fine-tuned model vs original model predictions and a short summary.

Alternatively, you may provide 5 examples and some extrinsic evaluation metric over many examples. For instance, you may use a different pre-trained toxicity score for option A. When dealing with human preferences, you may choose to [enlist actual humans](https://toloka.ai/) or [ask GPT4/Claude](https://arxiv.org/pdf/2304.03277.pdf) to compare your model's predictions. For task C, when optimizing for simple rewards like sentence lengths, it is enough to compare histograms of rewards (e.g. average lengths).

# Reward model

### Я использую датасет: "Yelp/yelp_review_full" с отзывами. Отзывы проранжированы от 0 до 4, где 0 - плохо, 4 - отлично. Я убрал оценку 2(как среднюю) и объединил 0 и 1 как плохой отзыв, 3 и 4 как хороший. Отзывов очень много, для ускорения я взял небольшой процент для обучения и стратифицировал выборку, чтобы плохих и хороших отзывов было равное количество.

In [ ]:
#!pip install trl==0.11.3 transformers==4.45.2

In [60]:
pip list

WARNING: Ignoring invalid distribution -ransformers (c:\users\aleksandr.egorov\ml\.venv\lib\site-packages)

Package                    VersionNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 24.3.1

-------------------------- ------------------

[notice] To update, run: python.exe -m pip install --upgrade pip

accelerate                 1.1.1

adjustText                 1.3.0
aiohappyeyeballs           2.4.3
aiohttp                    3.11.2
aiosignal                  1.3.1
albucore                   0.0.20
albumentations             1.4.21
annotated-types            0.7.0
antlr4-python3-runtime     4.9.3
anyio                      4.6.2.post1
argon2-cffi                23.1.0
argon2-cffi-bindings       21.2.0
arrow                      1.3.0
asttokens                  2.4.1
async-lru                  2.0.4
async-timeout              5.0.1
attrs                      24.2.0
axial_positional_embedding 0.2.1
babel                      2.16.0
beautifulsoup4             4.12.3
bleach                     6.2.0
bleuscore                  0.1.3
blis                       0.7.11
bs4                        0.0.2
catalogue                  2.0.10
certifi                    2024.8.30
cffi                       1.17.1
charset-normalizer         3.4.0
click                      8.1.7
cloudpathlib               0.20.0
cloudpickle                3.1.0
colorama                   0.4.6
comm                       0.2.2
confection                 0.1.5
contourpy                  1.3.1
cursor                     1.3.5
cycler                     0.12.1
cymem                      2.0.8
dask                       2024.11.2
dask-expr                  1.1.19
datasets                   3.1.0
DAWG-Python                0.7.2
de-core-news-sm            3.7.0
debugpy                    1.8.8
decorator                  5.1.1
defusedxml                 0.7.1
dill                       0.3.8
docker-pycreds             0.4.0
docstring_parser           0.16
einops                     0.8.0
en-core-web-sm             3.7.1
et_xmlfile                 2.0.0
eval_type_backport         0.2.0
evaluate                   0.4.3
exceptiongroup             1.2.2
executing                  2.1.0
faster-coco-eval           1.6.5
fastjsonschema             2.20.0
filelock                   3.16.1
fonttools                  4.55.0
fqdn                       1.5.1
frozenlist                 1.5.0
fsspec                     2024.9.0
future                     1.0.0
gdown                      5.2.0
gensim                     4.3.3
gitdb                      4.0.11
GitPython                  3.1.43
graphviz                   0.20.3
h11                        0.14.0
halo                       0.0.28
hezar                      0.42.0
httpcore                   1.0.7
httpx                      0.27.2
huggingface-hub            0.26.2
idna                       3.10
importlib_metadata         8.5.0
intel-openmp               2021.4.0
ipaddress                  1.0.23
ipykernel                  6.29.5
ipython                    8.29.0
ipywidgets                 8.1.5
isoduration                20.11.0
jedi                       0.19.2
Jinja2                     3.1.4
joblib                     1.4.2
json5                      0.9.28
jsonpointer                3.0.0
jsonschema                 4.23.0
jsonschema-specifications  2024.10.1
jupyter                    1.1.1
jupyter_client             8.6.3
jupyter-console            6.6.3
jupyter_core               5.7.2
jupyter-events             0.10.0
jupyter-lsp                2.2.5
jupyter_server             2.14.2
jupyter_server_terminals   0.5.3
jupyterlab                 4.2.6
jupyterlab_pygments        0.3.0
jupyterlab_server          2.27.3
jupyterlab_widgets         3.0.13
kiwisolver                 1.4.7
langcodes                  3.4.1
language_data              1.2.0
lightgbm                   4.5.0
lightning-utilities        0.11.8
local-attention            1.9.15
locket                     1.0.0
log-symbols                0.0.14
marisa-trie                1.2.1
markdown-it-py             3.0.0
MarkupSafe                 3.0.2
matplotlib                 3.9.2
matplotlib-inline          0.1.7
mdurl                      0.1.2
mistune                    3.0.2
mkl                        2021.4.0
mpmath                     1.3.0
multidict                  6.1.0
multiprocess               0.70.16
murmurhash                 1.0.10
nbclient                   0.10.0
nbconvert                  7.16.4
nbformat                   5.10.4
nest-asyncio               1.6.0
networkx                   3.4.2
nltk                       3.9.1
notebook                   7.2.2
notebook_shim              0.2.4
numpy                      1.26.4
omegaconf                  2.3.0
opencv-python              4.10.0.84
opencv-python-headless     4.10.0.84
openpyxl                   3.1.5
overrides                  7.7.0
packaging                  24.2
pandas                     2.2.3
pandocfilters              1.5.1
parso                      0.8.4
partd                      1.4.2
peft                       0.5.0
performer-pytorch          1.1.4
pillow                     11.0.0
pip                        24.0
pip-chill                  1.0.3
platformdirs               4.3.6
plotly                     5.24.1
preshed                    3.0.9
prometheus_client          0.21.0
prompt_toolkit             3.0.48
propcache                  0.2.0
protobuf                   5.28.3
psutil                     6.1.0
pure_eval                  0.2.3
pyaml                      24.9.0
pyarrow                    18.0.0
pycocotools                2.0.8
pycparser                  2.22
pycryptodomex              3.21.0
pydantic                   2.9.2
pydantic_core              2.23.4
Pygments                   2.18.0
pymorphy3                  2.0.2
pymorphy3-dicts-ru         2.4.417150.4580142
pyparsing                  3.2.0
PySocks                    1.7.1
python-dateutil            2.9.0.post0
python-json-logger         2.0.7
pytz                       2024.2
pywin32                    308
pywinpty                   2.0.14
PyYAML                     6.0.2
pyzmq                      26.2.0
RapidFuzz                  3.10.1
referencing                0.35.1
regex                      2024.11.6
requests                   2.32.3
rfc3339-validator          0.1.4
rfc3986-validator          0.1.1
rich                       13.9.4
rpds-py                    0.21.0
ru-core-news-sm            3.7.0
ruff                       0.6.9
sacremoses                 0.1.1
safetensors                0.4.5
scikit-learn               1.5.2
scipy                      1.13.1
seaborn                    0.13.2
Send2Trash                 1.8.3
sentence-transformers      3.1.1
sentencepiece              0.2.0
sentry-sdk                 2.18.0
setproctitle               1.3.4
setuptools                 75.5.0
shellingham                1.5.4
shtab                      1.7.1
simsimd                    6.0.5
six                        1.16.0
smart-open                 7.0.5
smmap                      5.0.1
sniffio                    1.3.1
soupsieve                  2.6
spacy                      3.7.5
spacy-legacy               3.0.12
spacy-loggers              1.0.5
spell                      0.48.9
spinners                   0.0.24
srsly                      2.4.8
stack-data                 0.6.3
starlette                  0.41.2
stringzilla                3.10.10
swifter                    1.4.0
sympy                      1.13.3
tabulate                   0.9.0
tbb                        2021.13.1
tenacity                   9.0.0
termcolor                  2.5.0
terminado                  0.18.1
thinc                      8.2.5
threadpoolctl              3.5.0
timm                       1.0.11
tinycss2                   1.4.0
tokenizers                 0.20.3
tomli                      2.1.0
toolz                      1.0.0
torch                      2.3.1+cu121
torchaudio                 2.5.0+cu124
torchmetrics               1.6.0
torchsummary               1.5.1
torchtext                  0.18.0
torchview                  0.2.6
torchvision                0.18.1+cu121
tornado                    6.4.1
tqdm                       4.67.0
traitlets                  5.14.3
transformers               4.45.2
trl                        0.11.3
typeguard                  4.4.1
typer                      0.13.0
types-python-dateutil      2.9.0.20241003
typing_extensions          4.12.2
tyro                       0.9.2
tzdata                     2024.2
uri-template               1.3.0
urllib3                    2.2.3
wandb                      0.18.7
wasabi                     1.1.3
wcwidth                    0.2.13
weasel                     0.4.1
webcolors                  24.11.1
webencodings               0.5.1
websocket-client           1.8.0
wheel                      0.45.0
widgetsnbextension         4.0.13
wrapt                      1.16.0
xxhash                     3.5.0
yarl                       1.17.1
zipp                       3.21.0

In [1]:
from datasets import load_dataset

ds = load_dataset("Yelp/yelp_review_full", split='train[:9%]').filter(lambda example: example["label"]!=2 )

ds = ds.train_test_split(test_size=0.5, stratify_by_column="label")

dataset = ds.sort(column_names="label")["train"].select(range(1835, 23515))

In [2]:
import collections
collections.Counter(dataset['label'])

Counter({1: 6028, 3: 5597, 4: 5243, 0: 4812})

In [3]:
# We'll be fine-tuning a small BERT-like model for now. Please try other models for the main assignment.
import torch
import transformers
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
reward_model = transformers.AutoModelForSequenceClassification.from_pretrained("distilbert-base-cased", device_map=device)
reward_tokenizer = transformers.AutoTokenizer.from_pretrained("distilbert-base-cased")

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [4]:
class YelpPairwiseDataset(torch.utils.data.Dataset):
    """ A dataset of all possible pairs of chosen and texts in TRT reward training format """
    def __init__(self, ds, tokenizer, accepted_label: int):
        super().__init__()
        self.tokenizer = tokenizer
        self.chosen_texts = [row['text'] for row in ds if row['label'] > accepted_label]
        self.rejected_texts = [row['text'] for row in ds if row['label'] <= accepted_label]
        self.column_names = ["input_ids_chosen", "attention_mask_chosen", "input_ids_rejected", "attention_mask_rejected"]
        assert self.chosen_texts, f"no texts with label {accepted_label}"
        print(f"Found {len(self.chosen_texts)} chosen and {len(self.rejected_texts)} rejected texts, {len(self)} pairs")

    def __len__(self):
        return len(self.chosen_texts) * len(self.rejected_texts)  # all pairs

    def __getitem__(self, index: int):
        chosen = self.tokenizer(self.chosen_texts[index // len(self.chosen_texts)], truncation=True)
        rejected = self.tokenizer(self.rejected_texts[index % len(self.chosen_texts)], truncation=True)
        return dict(input_ids_chosen=chosen['input_ids'], attention_mask_chosen=chosen['attention_mask'],
                    input_ids_rejected=rejected['input_ids'], attention_mask_rejected=rejected['attention_mask'])

In [7]:
TARGET_LABEL = 1   # and make sure it works by reviewing the sample printed below
reward_data = YelpPairwiseDataset(dataset, reward_tokenizer, accepted_label=TARGET_LABEL)

sample = reward_data[10000]
print('CHOSEN:', reward_tokenizer.decode(sample['input_ids_chosen']))
print('REJECTED:', reward_tokenizer.decode(sample['input_ids_rejected']))

Found 10840 chosen and 10840 rejected texts, 117505600 pairs
CHOSEN: [CLS] Nice airport with good dining choices. The US Airways Lounge is great too. [SEP]
REJECTED: [CLS] Went in for the living social deal last Friday. It was busy during happy hour. Seemed like the spot to be! Although, once my boyfriend and I were seated and advised the server that we had the living social deal, the service was extremely disappointing. I understand that with coupons at restaurants servers don ' t always get tipped on the price before discount. I used to be a server and restaurant manager and have seen that happen a lot. The server was very robotic and not friendly at all. She set down our drinks and food like we were in her way and troubling her. The appetizers were fair for pub food. The pretzels were pretty tasty actually! We really enjoyed the beer sampler that we each got as well! My favorites were the hefeweizen and vanilla porter. Everyone else that worked there seemed very pleasant and friendly except our server. We most likely wont be going there again due to the service. Hopefully the 40 % tip that my boyfriend left will help get that server ' s attitude turned around towards future diners! [SEP]

In [8]:
import trl

training_args = trl.RewardConfig(  # like transformers.TrainingArguments
    output_dir="reward_model",
    per_device_train_batch_size=32,
    gradient_accumulation_steps=1,
    learning_rate=1.41e-5,
    max_steps=1_000,              # note: training may need more than 1k steps
    logging_steps=50,
    gradient_checkpointing=True,  # reduce memory usage but train ~30% slower
    gradient_checkpointing_kwargs={"use_reentrant": False},
    fp16=True                     # disable this on CPU or on very old GPUs
    # you may add any other hyperparameters that you found useful in weeks 5-7
)

trainer = trl.RewardTrainer(
    model=reward_model,
    args=training_args,
    tokenizer=reward_tokenizer,
    train_dataset=reward_data,
    peft_config=None,  # optionally, you may tune with LoRA, prompt-tuning, etc
)

trainer.train()

C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\trl\trainer\reward_trainer.py:182: UserWarning: When using RewardDataCollatorWithPadding, you should set `max_length` in RewardConfig. It will be set to `512` by default, but you should do it yourself in the future.
  warnings.warn(
C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\trl\trainer\reward_trainer.py:199: UserWarning: When using RewardDataCollatorWithPadding, you should set `remove_unused_columns=False` in your RewardConfig we have set it for you, but you should do it yourself in the future.
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: aleksegorov1312 (aleksegorov1312-aimasters). Use `wandb login --relogin` to force relogin

You're using a DistilBertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\transformers\tokenization_utils_base.py:2847: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

C:\Users\aleksandr.egorov\ml\.venv\lib\site-packages\transformers\tokenization_utils_base.py:2847: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

TrainOutput(global_step=1000, training_loss=0.06505316001176834, metrics={'train_runtime': 1216.1758, 'train_samples_per_second': 26.312, 'train_steps_per_second': 0.822, 'total_flos': 0.0, 'train_loss': 0.06505316001176834, 'epoch': 0.0002723274465216977})

In [9]:
reward_model.gradient_checkpointing_disable()
reward_model.eval()

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [45]:
with open("./reward_review_model_checkpoint.pth", "wb") as fp:
    torch.save(reward_model.state_dict(), fp)

In [18]:
for sample_index in 45, 15000:
  print('TEXT:', dataset[sample_index]['text'])
  inputs = reward_tokenizer(
      dataset[sample_index]['text'], truncation=True, return_tensors='pt').to(device)
  with torch.no_grad():
    reward = reward_model(**inputs).logits[0, 0].item()
    print("REWARD:", reward)
  print('LABEL:', dataset[sample_index]['label'])
  print()

TEXT: We wanted to try some Japanese food. A nameless coworker of mine suggested Ichi Ban, located on Alma School and Baseline Rd. Apparently he told us that he had drove by it and thought it would be worth a try. He must have drove by it drunk. The appearance of the building is simply a monstrosity in and of itself. The architects must have been on acid when they designed it because it is such an eye sore. I keep hearing in my head, \"..don't judge a book by its cover\", yet my judgments usally end up being correct. \n\nWhen we walked into the establishment that is Ichi Ban there was nobody in there. I mean it was totally dead. At that moment I felt that if we continued to sit down and eat we might just die. Ichi Ban had Kitchen Nightmare written all over it. I mean, if when you walk into a restaurant and nobody is there take that as a sign from God not to eat. So we sat down and ordered some food. \n\nEverybody got soup. I guess it came with your meal. I didn't try the soup myself, but I looked around and watched as others did. And the reaction on their faces told me that it probably tasted of dishwater. A while after we got our soup our main courses arrived. I had the Teriyaki Chicken. Let me say that the rice was mushy and the chicken was cold. I could hardly eat any of it. The chicken was served on top of a nasty piece of lettuce that just made me want to barf. Forgive me if I am being a little sensational here, I am trying to make up for the lack of sensation I had when eating the food. Two of my other coworkers had some noodle dish of which they complained that there wasn't enough chicken in it. \n\nAs we were eating what we could I saw the cook at the sushi bar premaking some food. There was nobody in the restaurant and I wondered who he was making all of it for. Clearly the food isn't prepared fresh and I could taste it in my own dish. I thought to myself, \"..how long ago was this chicken cooked, because it is cold now.\" I must say that Ichi Ban had one thing going for it, great tasting Coke. \n\nAfter we finished, we got the bill and it ended up costing me $12! I normally don't complain about prices. I'm not poor. But for what we got, it just wasn't worth it. I was pissed. Perhaps I had been a bad boy and maybe that is why I got such horrible food. As we left we all decided not to come back, thank God. I wonder how long Ichi Ban will last before it goes under. It looked and tasted pretty grim.
REWARD: -5.234375
LABEL: 0

TEXT: I like this place...Saw dust on the ground, country music in the back, great views, and a small slide to get you into the restaurant. I went last night with my son. A balloon guy and magician approached our table and made waiting for our food fun. I might normally have been annoyed because I had to tip but, because I had my son I was truly grateful. Free cotton candy with dessert! And quite possibly the best chocolate cake anywhere. Yes, I just said that! It's true!
REWARD: 5.76171875
LABEL: 3

In [19]:
import pandas as pd
def reward_sanity_check(ds, labels=None):
    if labels is None:
        labels = []
        rewards = []
    for idx, i in enumerate(ds):
        labels.append(i["label"])
        inputs = reward_tokenizer(
          i['text'], truncation=True, return_tensors='pt').to(device)
        with torch.no_grad():
            reward = reward_model(**inputs).logits[0, 0].item()
            rewards.append(reward)
    return labels, rewards 
    
label, rewards = reward_sanity_check(dataset)

In [20]:
stat = pd.DataFrame([label, rewards]).T.rename(columns={0:"label", 1:"reward"})
stat

       label    reward
0        0.0 -5.113281
1        0.0 -5.128906
2        0.0 -5.343750
3        0.0 -1.628906
4        0.0 -5.265625
...      ...       ...
21675    4.0  5.613281
21676    4.0  1.496094
21677    4.0 -0.365234
21678    4.0  2.191406
21679    4.0  4.835938

[21680 rows x 2 columns]

### Train Доля правильных reward для положительных отзывов(выбраны как таргетные)

In [21]:
stat[(stat["label"] > 1) & (stat["reward"]>0)].shape[0]/stat[(stat["label"] > 1)].shape[0]

0.967619926199262

### Доля правильных reward для отрицательных отзывов

In [22]:
stat[(stat["label"] <= 1) & (stat["reward"]<=0)].shape[0]/stat[(stat["label"] <= 1)].shape[0]

0.9618081180811808

In [32]:
ds = load_dataset("Yelp/yelp_review_full", split='test').filter(lambda example: example["label"]!=2 )

ds = ds.train_test_split(test_size=0.25, stratify_by_column="label")

dataset_test = ds["test"]

In [34]:
import collections
collections.Counter(dataset_test["label"])

Counter({1: 2500, 4: 2500, 0: 2500, 3: 2500})

In [35]:

label, rewards = reward_sanity_check(dataset_test)

stat = pd.DataFrame([label, rewards]).T.rename(columns={0:"label", 1:"reward"})
stat

      label    reward
0       1.0 -4.101562
1       4.0  5.726562
2       0.0  5.410156
3       3.0  4.570312
4       0.0 -4.769531
...     ...       ...
9995    3.0  5.714844
9996    4.0  5.718750
9997    1.0 -5.269531
9998    3.0  5.386719
9999    0.0 -5.285156

[10000 rows x 2 columns]

### Test Доля правильных reward для положительных отзывов(выбраны как таргетные)

In [36]:
stat[(stat["label"] > 1) & (stat["reward"]>0)].shape[0]/stat[(stat["label"] > 1)].shape[0]

0.9488

### Доля правильных reward для отрицательных отзывов

In [37]:
stat[(stat["label"] <= 1) & (stat["reward"]<=0)].shape[0]/stat[(stat["label"] <= 1)].shape[0]

0.9414

### reward модель строилась как в примере, выше показал, что она хорошо назначает награды и на train и на test наборе.

# RL fine-tuning

### В качестве модели, которую будем файнтюнить выбрал "defex/distilgpt2-finetuned-amazon-reviews", так как она тоже предобучена на отзывах (но уже амазона). И при этом у нее нет смещения в сторону положительных или отрицательных отзывов.

In [38]:
from typing import List
def compute_reward(texts: List[str]) -> torch.Tensor:
  inputs = reward_tokenizer(texts, truncation=True, padding=True, return_tensors='pt').to(device)
  with torch.no_grad():
    return reward_model(**inputs).logits[:, 0]

In [54]:
import peft
peft_config = peft.LoraConfig(
    task_type=peft.TaskType.CAUSAL_LM, r=32, lora_alpha=32, lora_dropout=0.1, inference_mode=False
)

# reload main model as AutoModelForCausalLMWithValueHead - with an extra head needed for PPO
main_tokenizer = transformers.AutoTokenizer.from_pretrained("defex/distilgpt2-finetuned-amazon-reviews")
main_tokenizer.pad_token = main_tokenizer.eos_token

main_model = trl.AutoModelForCausalLMWithValueHead.from_pretrained("defex/distilgpt2-finetuned-amazon-reviews", device_map=device)
main_model = peft.get_peft_model(main_model, peft_config, adapter_name='default')
main_model.print_trainable_parameters()

trainable params: 589,824 || all params: 82,503,169 || trainable%: 0.714910720580927

In [41]:
# Note: this code is specific to IMDB; you will need to re-write it for other tasks

import torch
import transformers


import trl
review_for_rlhf = dataset.filter(lambda row: len(row['text']) < 200, batched=False)
review_for_rlhf = dataset.remove_columns(['label'])
sample_length = trl.core.LengthSampler(2, 8)  # use the first 2-8 tokens as query

def select_query_and_tokenize(sample):
    query_ids = main_tokenizer.encode(sample["text"])[: sample_length()]
    sample["query"] = main_tokenizer.decode(query_ids)  # query is the only required column
    sample["input_ids"] = query_ids  # to avoid re-tokenizing later
    return sample  # we do not need the rest - it will be generated by the model

review_for_rlhf = review_for_rlhf.map(select_query_and_tokenize, batched=False)
review_for_rlhf.set_format(type="torch")

Map:   0%|          | 0/21680 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (1232 > 1024). Running this sequence through the model will result in indexing errors

In [62]:
with open("./reward_review_model_checkpoint.pth", "rb") as fp:
    state_dict = torch.load(fp, map_location="cpu")
    reward_model.load_state_dict(state_dict)
    reward_model = reward_model.to(device)

In [55]:
training_args = trl.PPOConfig(
    model_name=main_model.config._name_or_path,
    gradient_accumulation_steps=1,
    learning_rate=1.41e-4,
    ppo_epochs=4,
    mini_batch_size=64,
    batch_size=64,# PPO performs this many updates per training batch
)

ppo_trainer = trl.PPOTrainer(
    training_args, model=main_model.model, tokenizer=main_tokenizer, ref_model=None,
    dataset=review_for_rlhf, data_collator=lambda data: dict((key, [d[key] for d in data]) for key in data[0])
)  # note: we pass main_model.model because PPOTrainer checks for one of several supported model types ...
# ... main_model.model is a model with adapters, which is supported. main_model itself is a wrapper that is not supported

In [56]:
from tqdm.auto import tqdm
max_steps = 20   # can be insufficient for some tasks - watch your learning curves
generation_kwargs = dict(
    min_length=-1, max_new_tokens=50, do_sample=True, top_k=0, top_p=1.0, pad_token_id=main_tokenizer.eos_token_id,
eos_token_id=main_tokenizer.eos_token_id,)
#                                  ^-- task-specific parameter!
with tqdm(enumerate(ppo_trainer.dataloader), total=max_steps) as progressbar:
  # note: ppo_trainer.dataloader is just a regular dataloader of queries, no RL-specific magic :)
  for epoch, batch in progressbar:
    if epoch >= max_steps:
        break

    # Rollout stage: generate continuations from batch queries using main_model
    response_tensors = ppo_trainer.generate(batch['input_ids'], **generation_kwargs)
    # ^-- list of tensors of token ids from main model tokenizer

    # de-tokenize responses to strings (since reward model uses a different tokenizer)
    batch["response"] = [main_tokenizer.decode(response.squeeze()) for response in response_tensors]
    # note: response_tensors already contain query tokens, so we don't need to add queries manually.
    # This may not be true for other tasks: check this manually by viewing batch["response"] and batch["query"]
    # Evaluation stage
    rewards = compute_reward(batch['response'])
    # Update stage
    stats = ppo_trainer.step(batch['input_ids'], response_tensors, list(rewards.split(1)))
    stats['rewards/mean'] = rewards.mean().item()

    print("-" * 30, 'STEP', epoch, '-' * 30)
    print(f'rewards/mean:\t{stats["rewards/mean"]:.9f}\t<---- average reward over this batch (higher=better, noisy)')
    print(f'ppo/returns/mean:\t{stats["ppo/returns/mean"]:.9f}\t<---- model-estimated average discounted reward')
    print(f'objective/kl:\t{stats["objective/kl"]:.9f}\t<---- how far we are from the original model (regularizer)')
    print()

    ppo_trainer.log_stats(stats, batch, list(rewards.split(1)))

  0%|          | 0/20 [00:00<?, ?it/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

------------------------------ STEP 0 ------------------------------
rewards/mean:	-0.281177521	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.553731918	<---- model-estimated average discounted reward
objective/kl:	0.000000000	<---- how far we are from the original model (regularizer)

------------------------------ STEP 1 ------------------------------
rewards/mean:	0.045897245	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.631238461	<---- model-estimated average discounted reward
objective/kl:	0.134747237	<---- how far we are from the original model (regularizer)

------------------------------ STEP 2 ------------------------------
rewards/mean:	-1.225526810	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.217734754	<---- model-estimated average discounted reward
objective/kl:	0.330352843	<---- how far we are from the original model (regularizer)

------------------------------ STEP 3 ------------------------------
rewards/mean:	0.128616333	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.638327003	<---- model-estimated average discounted reward
objective/kl:	0.571970224	<---- how far we are from the original model (regularizer)

------------------------------ STEP 4 ------------------------------
rewards/mean:	0.639225006	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.786328912	<---- model-estimated average discounted reward
objective/kl:	0.800090432	<---- how far we are from the original model (regularizer)

------------------------------ STEP 5 ------------------------------
rewards/mean:	0.428668976	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.692207754	<---- model-estimated average discounted reward
objective/kl:	0.829158247	<---- how far we are from the original model (regularizer)

------------------------------ STEP 6 ------------------------------
rewards/mean:	0.247133255	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.588566422	<---- model-estimated average discounted reward
objective/kl:	1.140507698	<---- how far we are from the original model (regularizer)

------------------------------ STEP 7 ------------------------------
rewards/mean:	1.071804047	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.818101883	<---- model-estimated average discounted reward
objective/kl:	1.382527590	<---- how far we are from the original model (regularizer)

------------------------------ STEP 8 ------------------------------
rewards/mean:	1.566096306	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.966771364	<---- model-estimated average discounted reward
objective/kl:	1.022593737	<---- how far we are from the original model (regularizer)

------------------------------ STEP 9 ------------------------------
rewards/mean:	0.150945663	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.481921583	<---- model-estimated average discounted reward
objective/kl:	0.674830496	<---- how far we are from the original model (regularizer)

------------------------------ STEP 10 ------------------------------
rewards/mean:	0.617160797	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.589243293	<---- model-estimated average discounted reward
objective/kl:	0.868169010	<---- how far we are from the original model (regularizer)

------------------------------ STEP 11 ------------------------------
rewards/mean:	1.103649616	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.739642382	<---- model-estimated average discounted reward
objective/kl:	0.794245899	<---- how far we are from the original model (regularizer)

------------------------------ STEP 12 ------------------------------
rewards/mean:	1.317442894	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	0.804802537	<---- model-estimated average discounted reward
objective/kl:	0.944695175	<---- how far we are from the original model (regularizer)

------------------------------ STEP 13 ------------------------------
rewards/mean:	1.963227272	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.031507969	<---- model-estimated average discounted reward
objective/kl:	0.805625379	<---- how far we are from the original model (regularizer)

------------------------------ STEP 14 ------------------------------
rewards/mean:	2.890842438	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.372677088	<---- model-estimated average discounted reward
objective/kl:	0.801079631	<---- how far we are from the original model (regularizer)

------------------------------ STEP 15 ------------------------------
rewards/mean:	2.787683487	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.373008847	<---- model-estimated average discounted reward
objective/kl:	0.700864732	<---- how far we are from the original model (regularizer)

------------------------------ STEP 16 ------------------------------
rewards/mean:	2.522444725	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.353572369	<---- model-estimated average discounted reward
objective/kl:	0.557187259	<---- how far we are from the original model (regularizer)

------------------------------ STEP 17 ------------------------------
rewards/mean:	2.594520569	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.430377007	<---- model-estimated average discounted reward
objective/kl:	0.203122318	<---- how far we are from the original model (regularizer)

------------------------------ STEP 18 ------------------------------
rewards/mean:	3.027045727	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.622089148	<---- model-estimated average discounted reward
objective/kl:	0.633947849	<---- how far we are from the original model (regularizer)

------------------------------ STEP 19 ------------------------------
rewards/mean:	3.578130722	<---- average reward over this batch (higher=better, noisy)
ppo/returns/mean:	1.850509644	<---- model-estimated average discounted reward
objective/kl:	1.128749371	<---- how far we are from the original model (regularizer)

In [57]:
ref_model = trl.AutoModelForCausalLMWithValueHead.from_pretrained("defex/distilgpt2-finetuned-amazon-reviews", device_map=device)
new = 0
old = 0
for i in range(10):

    inputs = main_tokenizer(["I think this product"] * 16, return_tensors='pt').to(device)

    new += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()
    old += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

### В качестве референсной модели берем "defex/distilgpt2-finetuned-amazon-reviews" и сравниваем средний reward до тюнинга с Lora и после. Разница есть:

In [58]:
print("mean reward before:", old/10)
print("mean reward after:", new/10)

mean reward before: tensor(-0.8653, device='cuda:0')
mean reward after: tensor(4.0462, device='cuda:0')

In [62]:
new = 0
old = 0
for i in range(10):

    inputs = main_tokenizer(["In my view"] * 16, return_tensors='pt').to(device)

    new += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()
    old += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

In [63]:
print("mean reward before:", old/10)
print("mean reward after:", new/10)

mean reward before: tensor(-0.7979, device='cuda:0')
mean reward after: tensor(3.9456, device='cuda:0')

In [65]:
new = 0
old = 0
for i in range(10):

    inputs = main_tokenizer(["I would say"] * 16, return_tensors='pt').to(device)

    new += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()
    old += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

In [66]:
print("mean reward before:", old/10)
print("mean reward after:", new/10)

mean reward before: tensor(-0.3320, device='cuda:0')
mean reward after: tensor(4.3473, device='cuda:0')

In [72]:
new = 0
old = 0
for i in range(10):

    inputs = main_tokenizer(["There is"] * 16, return_tensors='pt').to(device)

    new += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()
    old += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

In [73]:
print("mean reward before:", old/10)
print("mean reward after:", new/10)

mean reward before: tensor(-0.2131, device='cuda:0')
mean reward after: tensor(3.4256, device='cuda:0')

In [76]:
new = 0
old = 0
for i in range(10):

    inputs = main_tokenizer(["I can"] * 16, return_tensors='pt').to(device)

    new += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()
    old += compute_reward([main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]).mean()

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

In [77]:
print("mean reward before:", old/10)
print("mean reward after:", new/10)

mean reward before: tensor(-0.2783, device='cuda:0')
mean reward after: tensor(4.0723, device='cuda:0')

### Отзывы, которая генерит модель после finetune более позитивные, как и ожидалось:

In [59]:
inputs = main_tokenizer(["I think this product"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

['I think this product is really helping with a high level of health, if you have any issues with the stomach it will be really helpful.It’s made for what you need in your car. It does take awhile to build up.Cute outfit. Super',
 'I think this product is really well made as well. And I would definitely buy it again as I love this product.I love it, I have to buy another book. I will look into other books and learn to like it, love it and give this amazing gift',
 'I think this product is great. My baby is much stronger which works ok. The battery does not go all the way to the side, so it is no easy to put together. So far, I like it so far.Easy to install with use. Perfect for',
 'I think this product is so sturdy. My kid loved it so much!I was very happy with this purchase even as it is a great product! And the quality of the knife is good!!I ordered these for a gift. The first one came broken when he took',
 'I think this product is a good replacement for my face itchy, but you can use a spray and moisturize it!Product looks good, fits exactly where I needed it, and I still love it!!Not super thin, but overall great idea for a comfortable chair',
 'I think this product may be the way to small but I’m not entirely sure if I can find a good product? I bought 3 sets of this from Amazon in 2 days and it works great!Candy was on display today and the color is nice.',
 "I think this product is a waste of money and is much cheaper than the one I bought. If it would be great I would highly recommend this product.I don't know how you feel or how quickly it holds this stuff! Great to take your face off, pillow",
 'I think this product will be a great upgrade to my Samsung Smart Cover , it looks well made & looks awesome in a room full of people.This is a great set of items from my home store. Looks good in my kitchen for the holidays! I will use it',
 'I think this product worked well for my son for a long time and was quick enough to save them back to some of their old equipment, and my kids seem to like it.Great for those who are not using this product at all.This item looks good so far',
 'I think this product will help me more consistently use the phone. I am going to buy more of that over again. Will use as long as I think they will continue to help.These are great pens with an awesome priceThe only issue that I have is they seem',
 "I think this product looks good. The material is good but was easy to clean, and it fit perfectly!!Perfect for my 6-8 yr-old's desk though!Very soft and fits rightMy dog loves that, this is great! It's on the shelf",
 'I think this product will hold up better. The fabric was sturdy. I ordered a medium size and it is holding up very well.Perfect for the price!Very well made and very very helpful.I like that when they pop up they are more flexible and comfortableNot',
 "I think this product should be used. It was well designed and looks great.I've have used it several times and the material is nice and easy to put onto the grill. I've used every single time I have seen a product on the market.Nice looking product",
 "I think this product will be useful in dealing with the flu.Just received the one I normally wear in the summer, it smells so nice and keeps my face up & face in great lighting. Easy to set up and great quality.Just what I'd hoped for.",
 "I think this product did a lot of good things for my wrist. I like the smell of it on my hands. They come in the same color as the most expensive brands I've tried, though.This was an awesome piece to watch all of my TV and podcasts",
 'I think this product will make my hair grow even more attractive. You’ll be pleased with that. I’ll be buying more to grow hair.The best product I have bought!Awesome idea , very practical!Perfect the size and style this has!']

In [67]:
inputs = main_tokenizer(["In my view"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

['In my view the whole concept goes at a great value in design and product. The main thing is the lights are very clear that I bought them because they are very bright. I also used them for camping from the beach to a lot. I also like their flexibility',
 "In my view all this is a pretty solid product.The little white tape that sticks into your ears has been helpful from my husband's journey. It is so soft!This is a perfect gift! We have several pairs of earbuds that stay in and stay",
 "In my view it is much smaller than the standard. My kids use it daily for 3 hours everyday but these are very thin and fit nicely. I'd recommend these for all schoolwork. I would recommend that they fit and not keep your ears warm and ears warm",
 "In my view... I have to use it to make a big bowl to toast it in this style. This bag is made of very good quality ingredients. It is so versatile and a great weight.So far I'm not convinced that these are anything different than a",
 'In my view of these, you can see the glass ceiling. But the glass is more durable. You get a lot of different things from your normal glass ceiling.I ordered two and they work as described. I was pleased.Excellent.I will say it was',
 'In my view of it , it is a really great setI am 5\'0" and I love it, it lasts the whole summer and has everything. It is perfect for everything!I am a big fan of the color scheme and have had a good result',
 'In my view that the product is not compatible or useful or made, it made me even more happy.Very soft but only 2 months old.Doesnt work well for our needs. I have 2 dogs which has been able to wear it for years. I will',
 'In my view of the band so have all that band in place. The top band is great for a while and will continue to get the job done. The material is durable, as it is on your feet and very comfortable to wear. I love that there is',
 'In my view from it, I was able to easily change up my bed so I can sleep, sleep, sleep, and sleep with my baby. A great case to carry the kid or other toys. It is also very handy. I plan to add more accessories',
 "In my view, the material looked a little thicker and the fabric was soft. It's not as soft as i expected. We also have a very thick weave pattern and the lining is very soft. The fabric is also solid, just like the picture said. But",
 "In my view of these, they are good - easy to use, and not too large! We've had good results and now are looking for a few more to protect our kids, and the very durable fabric! I will update all the next time!Nice quality",
 'In my view they look so good and soft and made my little girl feel so alive.I loved it until the last 2 or 3 years and i have used it everyday now and it makes an awesome look!I like the ease of setup and I have two batteries',
 'In my view that I was supposed to have a small bag and it made me very happy, I am not an expert on anything, and it is not easy to use, I used it to remove excess and then put it back in which is great. Would recommend',
 'In my view there is nothing I think they can do with the sound. When I play the music they create a lovely soft and beautiful sound.Love this! It has everything you need to give me great love and use it.Beware of product, good quality',
 "In my view this is for a replacement. I really like these brushes and can't complain about having to fill a paint brush every time I carry it in I need a replacement brush.Love this but they do not last very long at all. But that is great",
 'In my view the color and the design makes it easier so I can use with my iPhone. But it does seem to work well.It is okay for my purpose as it is a small itemI wanted to like this book but it started falling off! It does']

In [68]:
inputs = main_tokenizer(["I would say"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

['I would say the quality and the price was good for all of us, just wish it came preinstalled.Easy application to a new job.I really enjoy it. No problem.It was an easy read book, I enjoyed reading it.Very durable. I',
 "I would say it is the best hairline mascara I use. It does the job of removing my eyeliner but it is a little thick in hair.Not overly impressed with the quality of this product.Works great! It's perfect with my phone but i really",
 'I would say this book gave me one of the best and super entertaining series of my adult life!This is exactly what it is. Very easy to read and a great way to set up I love so very much! It has great taste and is a wonderful addition',
 'I would say this is a good product as well as the tools. It is a little heavy, but the light weight is great for my work and my wife is really handy.Works great.Great price so far so happy with the product.I love the recipes',
 'I would say the product works. The way it is used to keep the water cold and cool is useful and helps keep the water from chimes.I love them. They do give you more power and energy. There are many little things on this package that I',
 "I would say a good case with no issues on the edges. Nice for the money.Great product.I had my dog start doing tricks at the park and I love it. He's had some great learning and she's quite a fan.This was my third",
 "I would say the product did a good job for us getting a clear and consistent look of the skin in our skin. This is a very pretty moisturizer and keeps my skin very clean. The only downside is that if it is not to heavy then it's not",
 "I would say, very good stuff, but not too strong. This one had its own zipper that was easy to do and easy to use. It's a nice design and comes with some extra slots.The price is good. Only problem is at a good price",
 'I would say 1 is quite heavy on the case. It’s okay and lightweight.This book was great until I got it. I just wish it was just a bit shorter. The story of how the relationship between the two families is different, especially during',
 "I would say I've received compliments on this product with great productGreat gift for the sonGreat for the first time with the pool. Perfect for our bathroom.Great, great fit and great buy - quality, durable and compact!Very good product. Wish there were",
 'I would say this one is the best and I will recommend to anyone!Great itemThe shirt is exactly what it was stated in. He wears it all the time with ease. I always get to travel when I do. Very pretty and fits perfect. It�',
 'I would say with the new battery it has good battery lifeI usually wear this all day, to make my daily life happier. Great price, but I have other brands. My daughter does still get a great workout!This chair has a nice design. It does',
 'I would say that if I had these and got it they would be great and work for all ages.This book has fun and it comes down well to me.Good story. I like it in its story!I like it very muchLove these. And they',
 'I would say they were a great value for small and small.I used it 3-4 times and loved them. Great buy!Easy install to take into account my needs. Perfect temperature. We have a small room on kitchen counter. Would very recommend! I',
 'I would say this item is great! A little tough to get it to work, but still works.I bought a black dress that had nice, comfy and cozy patterns and it fit a great style, especially with the jacket. He has so many compliments on',
 'I would say they are the same size and comfortable as new! I think they are a great value for you.Good read, very clear in this great new book on psychology and what the world needs a good one, and an unexpected story of love and love.']

In [74]:
inputs = main_tokenizer(["There is"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

["There is a small space. Easy to assemble.Great for what you need it for to work and it is as pictured. Only problem is its very light to it.Doesn't like the price!This is a great product. I can’t",
 'There is a good way to use your hands.I used this for a vacation or picnic and this product was my go hand and it arrived promptly.These bags are nice but the price is too expensive. They are a little thicker than some other bags I have',
 "There is a good case. But is not very heavy or strong enough to fit all my phones in the car. It's the best. I have had trouble sleeping this case and that has helped me. It really did get my mind spinning. We were not",
 'There is no odor or a soft finish.These headphones do what we need on a normal car ride. I just wish it was on longer.Great gift for my granddaughter. The only thing I do that she loves it so much.Came with instructions.',
 'There is always a problem with the first ones I used when a little bit stiff. But not in the back yet, this is a great alternative to this stuff.It looks good for a few hours, but the material is also soft, I found out I',
 'There is no "backlight" in the design! I\'m not sure what\'s the future of this.They seem to be very durable, so I\'ll keep it!The product is a wonderful gift. A simple to use product, but is a little',
 'There is not enough flavor in the dish.Very well made and well received productGood size to go around.I was very impressed with the quality, and this is an inexpensive way to store. I do recommend the products.I enjoy its flavor. Easy to',
 'There is a nice color to them. However I am very disappointed that the fabric is not well built. It is just the wrong material, made in China and the quality is good.I love the quality but the color is what it should be and i feel',
 "There is no mention that the item was specifically made for the grill, that's why I had it. I don't live in America, for instance. Maybe they should not be, I'm really happy with this product.Good material, fit, and not",
 'There is the first 2 in the series. They seem to be just the same and better. I am very pleased with the variety of colors and the variety of styles.My favorite part is this was so good for me! I use this for my garden,',
 "There is not sure how this works. The light worked, but it's still good to see some of the lights!I like to wear these with socks. But I didn't realize how comfortable in a summer. I keep them because they're cute in the",
 'There is no use to this toy, a bit too loud and my hand comes downThe material is nice but very softLooks great on my counter. It was very well made. Thank you for a great product.My dog used this and loves it.Love',
 'There is a nice quality but there are some issues. This is for a small dog with a loose nose. The dog can get over it and is able to chew it when they are up. Other than that it does seem well. I have a 7,',
 "There is a bad idea by the author but does the whole story. I would have given less star if you could have had the books so much better.One star that I can return is the sound which is quite loud so it's a good choice. I",
 "There is a great purchase for the priceNice and very sturdy, easy installation. Easy to use.Bought this as a replacement and I love it!!It doesn't suck at all that great, but you can go through so many.I like the fact",
 'There is that the battery is so easy, when using this on my car I noticed a huge difference in the wind.I love this product as much as the product you need it to make.This bag is perfect and the length seems pretty well done.A']

In [78]:
inputs = main_tokenizer(["I can"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

["I can't understand the other flavors (like chocolate), so I think that I won't be able to understand them for a while, so I will try that at later. The flavor is good.I love all 3 flavors, it is very sweet and perfect",
 'I can think of many ways to control your posture and how it can assist the child. The concept of this set was so nice and simple to get off it!I like you to use it. You get what you pay for.I just installed in my',
 "I can see it is being used by some. I can see it going with a little weight but the fact that it's so light and does look neat, is worth the price.Good battery, works as advertised. I used it as both a battery and",
 "I can see the difference in other ways that I use the product. Very happy with this product. I have one more bag for use in the office to have more space for cooking that I have that's more convenient for me and a little larger than I usually",
 'I can see where the sun goes and if I can do anything with this, I will go ahead and purchase another one. The battery is great, I haven’d had to return it.A bit small for my small arms, but a bit larger',
 'I can use this light without needing special tools or a screwdriver. The light doesn’t come through as well as is shown in the video. The light also doesn’ve enough grip to get any dirt off of the vehicle. So it�',
 'I can use a pair of earrings which is a pretty nice addition to my little set and I like the way they fit on my head. They have always been so comfortable and easy to put on!Bought this for my granddaughter and she love it!',
 "I can't go wrong with each product. I'm very satisfied with a new quality.I ordered one. The other was smaller too. Just received for the summer.Great idea and very clear instructions on how to set up. I love everything about this product",
 'I can have it at a nice price with a small side for a coffee.I really like the taste, it seems to be well made to give you the energy that you like at work. Its a really good size for a cold dog or some pets.',
 'I can see how it was received. I was really excited about my characters.My granddaughter loves these! Thank you!I like the look and the look and the fit.I loved the set! I’ve only used the pump a lot and the',
 "I can't rate it for durability, but so good!Good gift for a long-time lover.The book is an informative introduction and a fun book.A wonderful book about his family and family. A love story, love the people and things you know",
 "I can't even use it yet. I'm happy with it. I like it good and love it!!!I have found a lot of people have been saying that these bags are the perfect size for traveling, especially the kitchen. They are a very good value",
 "I can just make my cat happy, don't think this was an expensive item and would be great for her to read.My daughter is always getting her pills & we have many in the same bottles. She is using a few of the bottles.Product itself",
 'I can easily return them and put the same bag to my dog for the price. The size is very helpful.Very thick, strong material for my hair.This is a great product.I bought these for my husband to help him stay clean with his hair',
 "I can't tell you how soft it is but its nice. I will have to take the phone off my couch and put in more water.Very soft, looks beautiful on my feet. Love the color and how compact its is and looks like real world.",
 "I can't get in to this at all. Don't purchase it again at the company.They are great. They are not as thick or the thin material. They work as I was hoping.This is an amazing book I am happy to read. It"]

### Отзывы, которая генерит модель до finetune более разношерстные(выше доля негативных):

In [61]:
inputs = main_tokenizer(["I think this product"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

["I think this product will help me sleep. Not sure if I have any issues going forward.My wife doesn't like it, the packaging goes weird every couple of days. The color in this pack looks a little strange. I had more of a blue color that was",
 "I think this product is not as useful as a shampoo line, so maybe I am wrong. Very nice and inexpensive.I can't use it without the other hand, and these are the best. They're smaller than expected, and are not a fan.Works as",
 'I think this product is well made and was only used once but it will last a week before breaking off and cracking. Also, the box came with a 2 inch jargie, even though it looked like it would be ok. I had other jars I was hoping for',
 "I think this product really is helping me to get people's attention. I do believe this is a really good product to really help them, because it's been working great for me. I have used so many times, I can feel the difference in my skin, I",
 'I think this product might be working well for a better quality control. Only thing I have is I had to use my own nail polish to get it to work. I will likely get another in the near future.Love this brand of hair...I love it...but',
 'I think this product will help with the headaches and pain that comes from arthritis for many people. I used a lot, but was so upset it didnt help with the headache.I used this for my 3 year old because my feet are so hard to walk on the floor',
 'I think this product was good quality and the size. However, its a thin cotton and I am very unsatisfied with the way it rolls. The way it is sewn is very disappointing. It does make the rolls somewhat flimsy and will get stuck in tight spots',
 'I think this product is better than I expected, so I was hesitant to spend the extra $100 to buy the original one of them. It will be more difficult for a woman to open the window for a new window to open. It is still a shame because while',
 "I think this product was the perfect size. I actually feel a little bigger as I've had this for about a week. I have to take it as a daily supplement for my energy boost just in case its going to drop.These are SO nice. They are perfect",
 'I think this product was not as advertised or what I was expecting. Still to be seen. My son loves seeing it when we’re in school and it’s on my wrist and the size of my purse is great. Definitely was ordering more and my',
 "I think this product is very sturdy and the material and material looks nice. I would not buy again.I haven't read other reviews on this product. The company offered to replace the phone with a larger version of the same phone. I would say very pleased though.",
 "I think this product is a great way to install the lights at home/room/work area/in my garage/home/work site. It works well and is not a big deal for me because when there isn't it, it's great. However, I",
 "I think this product is worth it, I got 4 packs.The battery seems good overallThis was supposed to be a replacement for my munching bowl. It wasn't. It had some sort of texture that wouldn't go away but my kid still liked it.",
 "I think this product could be better. I don't think it's worth the money but my husband and I have very small hands so I feel that the product can be used for a variety of different purposes . I just know that I will try and use it in certain",
 "I think this product has no good ingredients. I do know that when we tried that bottle, it didn't taste too bad. The product seems to be very nice, especially in regards to the high taste. I am actually hoping to try a better one once I have",
 'I think this product does the job, but this product was very slow, and I couldn’t find any way to take it out of my mouth so I had to add an electric chair to the lid! Also, it did NOT work!Did not work for']

In [69]:
inputs = main_tokenizer(["I would say"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in main_model.model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

["I would say they're the best.Love these glasses! Great for my husband looking to make homemade beverages. Not too bulky and comfortable just for one bottle. Not too bulky just to fit right.Works well for working with my kidsI am impressed by this product",
 'I would say this movie was a good way to make a movie about something but so did the premise and that is what i loved about it.It was a good workout routine and very well-made. My son is 6 months old when we get a run at',
 'I would say this review was a very well written, well researched, informative, thorough read book and is a good read to read.This is a nice product and fits perfectly. My dog absolutely loves the extra soft drinks and this helps her a lot as she loves',
 "I would say that these did NOT fit my hair on the phone. They are a little shorter than I expected.Not very sturdy and makes the job a little easier. But this is my 5th Birthday and it's been a great season since. I haven't",
 'I would say that this is a quality product. I was so happy. I am a size 6.5, 190 lbs and I am pretty lightweight and fit like new.I like it for the price. It has a great look and function. I really',
 "I would say it was very easy on the knees....easy to get a grip on...the waist just doesn't hold up.I am a regular person and this bag was awesome!I love this bag! I have worn the case 3 times (4+ times",
 'I would say no more for these people.These are so cute and comfortable. They make a very thin film on the sides that I think would have saved myself a lifetime. I have never been a mop man so comfortable to go out in.I use it',
 'I would say this is way better to get a little more control on the skin tone than the standard gel (the real thing though) so that I can use it to get it done.I purchased this for the second one on my son. His birthday. Thank',
 'I would say good quality.Great for a kid’s kitchen table.I like these little bowls for easy cleaning.I liked the flavor and how it came together. Just like the flavor. And it is easy to use and keep in case. I use',
 'I would say these are pretty good. But after a few months in use they have not fallen off at all.Bought this for my 2 daughters and she loves it.I love it sooooooo! I love that I have 5.5ft in shorts',
 'I would say I read the book in full, a good way to keep you connected. Very useful in organizing a library!It is cute but not effective for small feetThe product looked amazing in our apartment. They last more than half a day then I used the',
 'I would say it would protect the screen and read through the case on the remote/watch and use with it at work. Otherwise this is good!I’ve owned a bunch of new phones here and it’s always beautifulI like this product!',
 "I would say I've just purchased this and am looking forward to a new one. I can't wait to wear it.I love the soft cotton purse and I ordered this for my husband for some reason. He loves it. The fabric looks great and the fabric",
 "I would say that it is made well, the little plastic is comfortable to move around, but does not feel so comfortable, it's just for you.Very happy!My son wanted to like it and it will definitely be buying moreI purchased this to use for",
 'I would say one of my favorite books from her novels. This book is a must- read for any young woman. Her family is in search of their doctor. The author is a writer and a great writer. This one fits perfectly in her. Enjoy what she',
 'I would say it gets dirty once you open the bag it’s pretty and smells like nothing to clean it is good. The only downfall is if the light is always on I can’t light it up anymoreI don’t like the price']

In [71]:
inputs = main_tokenizer(["I would say"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

['I would say the color of this bottle is very nice. It seems nice. The black ink color does not like the quality and consistency. However, it’s not quite the one I bought from a different retailer. It’s a medium size bottle',
 'I would say the screen protector is a little more bulky than I would like. It fits the phone with a case and there is enough room in the case on my watch to take and look at it for a few hours. I don’t feel like wasting',
 'I would say I’ve enjoyed the series pretty much without the actors. A wonderful book.I think i got one to rate the reviews on this brand because I like the idea of these things, but one of the other items that I was happy with was',
 'I would say the only downside was that it did not stick well. It would not stick to the car. The screen protector was already broken after about 8 months of use.Didn’t get what I paidI ordered the same size up and ordered this',
 "I would say that it would be great if it could hold more paper, but, as time goes, it would work great. I've found this to be difficult to use and is not effective at blocking it. I would recommend this at least for those who are",
 'I would say they’ve been good product for the price. My only complaints was that in the bottom half of the head rest was not enough padding and I never wore it.It is great, but I am stuck with the old fashioned way of holding my',
 "I would say it is very well made, especially for some people. I'm looking for some very well made, really sturdy and high quality rubber that protects your car. The key pad does not fall out and you have to remove or tighten the handle if you are",
 'I would say the top for an adult can do a better job with the bottom. However, I had to go find another brand to buy.Nice color but didn’t seem like it would hold all 4s. Very disappointed.These do not go over',
 'I would say this product is fine for the price and not any bad for the price of a couple pairs of headphones.This product is very flimsy. The first day it broke I returned it. I did not know this was a defect. The second day I',
 "I would say that you can't stop your hair but this one only lasts about a minute...it starts to fall apart once you start getting rid of the roots. It's pretty messy but you don't end up with a dead thing.Not very soft, but",
 'I would say for those looking for better compression. I believe this product is actually a good product!It is a great product to have on your dash screen! My one problem with all this is the button on my dash! I am sure as soon as I go',
 "I would say this is more like a black one. The material is nice. Definitely do not recommend this material.Works great to me. Nice. Only disappointed it doesn't work so often. I only wish it did a little more of a job of locking up",
 'I would say that these are cute because the box itself is extremely thick and soft. For $50 you do get the product however with this box, it’s not very long lasting, but I really like those colors and the smell. I bought the extra',
 'I would say this book helped me a lot. I wish there was one page. I have read it alot during the trip. I didn’t just check on my phone everyday. I also had it for the first time since it was sent. It also',
 "I would say that my original camera was made well. But since the frame is only one meter from front, the picture quality has changed. I've had to send it back and see if they're happy I'll buy another one.I haven’t given",
 'I would say I am getting tired of the fact that I got my hair cut out of this product! It feels super-easy to remove it from my hair and it is pretty soft. I put it in my makeup and it absorbs as well. Very nice.']

In [75]:
inputs = main_tokenizer(["There is"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

['There is a bit hard to find a good and durable product.I use these as a tool to install oil filters. The most beautiful thing about these is they do not stop the flow and get hot in the shower. I had no issues with heat.This',
 'There is this table top with a picture of the contents of the top making it very inconvenient to look at the full contents. I ended up ordering 2 items not very useful. All the items I needed were used, and the picture showed the table front. As',
 'There is no way to see if it is a big deal for a smaller brand but I could see it being a larger sizeThis was a great case for my iPad Pro, I have small hands, but my MacBook Pro 8 Pro 9 is an XL. It',
 'There is a good set of lights that can be adjusted and controlled and work great for any setting. This is super easy to install and clean. Love it!Works great in my office but one problem is the wire came apart. Once it’s together',
 "There is no help and is basically worthlessI have had this since Christmas and it works really good and not as nice when you have a large dog. So nice to have a cute little blanket and it feels so comfortable. I didn't use it all the time",
 'There is no instructions how to install. I was able to use a power switch that I had attached to a speaker wall plug and then when it was plugged in, the signal would be out which made my speaker unusable - I will not be changing this switch',
 'There is a nice price and I can say nothing about it and I am happy with it.I am a true believer in God and to believe God has revealed me to anyone. I am the only person not very strict. I want to believe that what I',
 'There is a very nice quality. The only problem is we had to return the shirt.They are really hard to open when using them. No instructions or instructions.I love trying to use this brush to cover my lips. This does not have the same effect',
 'There is my first review because it has been several months. When I had my problem with this I had to go through more of it to get a quick fix. If you need to upgrade all of the screws, I recommend this product.I have purchased 2',
 "There is a little hard and needs to be cleaned after one washing. I can see the scratches on the plastic at the corners but it's great as you can still see the paint everywhere without wiping the plastic off.Worked as is. Just bought a second",
 "There is such a nice shirt when you want one to be a little snug.. and it's actually very cute. I'm a little disappointed by the color of my shirt being too long of a length and so much less than i thought it would be. If",
 "There is a lot of fun at this time but I need more! I know for sure if I need to just buy a different product.I was looking for a size smaller for a kid so I wanted something that fit my dog's mouth. But it doesn",
 'There is an extremely powerful solar cell. It’s a really good set. Good for the price.Very useful little gadget of the future.My husband enjoys this product. It gives him great balance and the look it gives him while putting on our bed',
 'There is still a bit of the story. I really wanted to like everything, but I needed to read it before I even went out there. It was just me trying to get an actual story line or something. It took so much more to end than I',
 'There is a great deal to see that in this case I only had one of these out of the first two. One of my daughters took it.Great product, exactly as I expected , I like the look, the product looks good, it has a soft',
 'There is not an option for any kind of person. I had to return it because I have a high school child. I could not return it because I ordered 1 year old for free. So I am returning it because I ordered a large and I have to']

In [79]:
inputs = main_tokenizer(["I can"] * 16, return_tensors='pt').to(device)

[main_tokenizer.decode(candidate.flatten().cpu().numpy().tolist()) for candidate in ref_model.generate(**inputs, max_new_tokens=50, do_sample=True)]

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

["I can't think of a better way to get the item shipped. I guess I'm going to keep it because I am so very disappointed in it!The price for this product is great. It comes with stickers on the side, but that’s",
 "I can't see it coming in a good way.I bought these for my daughter and her mother after Christmas! She loves them!!! I am so grateful I got my daughter to wear those! They are a bit stretchy and the fit is very nice!",
 "I can't wait to get the bottle in. And this is the last bottle we will have to put this bottles out. So much fun when these are in a box full of stuff.Awesome but a little stiff. Looks to be a sturdy design.Nice",
 "I can't remember much about this book... I read the first three parts, but it's still a great novel!I thought it was the product I was looking for.Very smallI love the size, although the fabric is a little tight, so I",
 'I can’t stand this. It is too difficult to move and it is difficult to keep on the chair. If you just want to keep on your chair, these are not going to do it. They are too tall. So not recommend.I',
 "I can't really use it because the button doesn't show the color. It doesn't even show the light. I have to have my eyes wet from some kind of cold after a few hours of useIt came in a damaged box, not even sealed.",
 "I can't speak to the longevity of the cord. Would have given 6 stars if I paid slightly more..It fit fine but not sturdy. It has a thin plastic inside that doesn't fit into anything on my wrists, and falls out easily. These cables",
 'I can not use the product for my project. There is no way with this product to return it due to the hassle of returning it.Do not waste your money. They were great for the first 6 months. They stopped working very quicklyThese are so cute',
 "I can still see some of the holes, but this was not worth the hassle of shipping them back. But after they're shipped, they're still excellent, they will last.The fabric is thin, seems like a good enough material but it does not seem",
 "I can't find this at first. Not a very reliable source. The seller says this is OK and I bought it in hopes that I would be able to try the product out of China for a better price. If you don't have the item I can",
 'I can only recommend this product.I bought this to use on my dogs sheared her paws without using any more force because it’s so heavy and not hard to put together. The top part has great support and also protects the sides. The bottom',
 "I can't say I like it and I can't really say for sure if it's for the scent itself and my cat won't bark. I'll say, I am just happy with it though. I really appreciate the fact that it is in the packaging",
 'I can really enjoy this game! I love it but the one issue I have with my 4 year old, it is very difficult to adjust to a normal game and very difficult to install. I put the controllers first, so I can adjust the height to give',
 "I can't tell if this book is a real book. It's so short. I wanted for my 11th birthday and it was way too short. I needed another book for my son he loves. He's always a bit afraid to write a really good",
 "I can't think of a better way to write this game without a dedicated game. I guess you get what you pay for.I had only used it a couple weeks and the bottle just kind of popped and fell off. I am sure this wasn't for",
 "I can't figure out how to put him on the phone!I got this dress with the band around my thighs and it was so comfortable to wear for a long time before it didn't get too warm. After the first wash I felt that it was uncomfortable"]